import type { ToolContent } from "./types";

const UPLOAD = (what: string, browser = true) => ({
  title: `Upload your ${what}`,
  body: browser
    ? `Drag your ${what} onto the upload area or click Choose file. It's read in your browser. Nothing is uploaded.`
    : `Drag your ${what} onto the upload area or click Choose file. It's sent over an encrypted connection to private, temporary storage for conversion.`,
  shot: 1,
});
const RESULT = (fmt: string) => ({ title: `Download your ${fmt}`, body: "Rename the file if you like and click Download. The result is ready in seconds.", shot: 3 });
const CLOUD = { title: "Secure cloud conversion", body: "Files are processed in an isolated container and deleted automatically after conversion, within 60 minutes at most." };
const PRIVATE = { title: "Converted in your browser", body: "Your file never leaves your device, so conversion is private and fast." };
const FREE = { title: "Free, no account", body: "No sign-up, no email and no watermark on the result." };

export const convertContent: ToolContent[] = [
  {
    slug: "pdf-to-word",
    keyword: "pdf to word",
    keywords: ["pdf to word converter", "convert pdf to word", "pdf to docx", "pdf to word free", "pdf to editable word"],
    metaTitle: "PDF to Word Converter Free: Convert PDF to DOCX | PDFella",
    metaDescription: "Convert PDF to Word for free in seconds. Get an editable DOCX with headings, bold text, images and page sizes kept. Runs in your browser, no sign-up.",
    h1: "PDF to Word converter",
    subtitle: "Turn any PDF into an editable Word document in seconds, right in your browser, with live progress for every page.",
    quickAnswer: "To convert PDF to Word, open PDFella's PDF to Word converter and drop your PDF onto the page. Conversion starts immediately in your browser and shows live progress for each page. When it reaches 100%, click Download to save the editable .docx file.",
    howToTitle: "How to convert PDF to Word",
    totalTime: "PT1M",
    steps: [
      UPLOAD("PDF"),
      { title: "Watch it convert", body: "Conversion starts automatically. A live percentage shows each page being read and rebuilt as Word paragraphs, headings and images.", shot: 2 },
      RESULT("Word document"),
    ],
    benefits: [
      { title: "Fast, in your browser", body: "No upload or queue. Most documents convert in a few seconds with live progress." },
      { title: "Editable paragraphs", body: "Lines are joined into real paragraphs, not one text box per line." },
      { title: "Formatting kept", body: "Headings, bold, italic, font sizes, alignment, images and page sizes." },
      FREE,
    ],
    sections: [
      {
        heading: "How the PDF to Word conversion works",
        body: [
          "A PDF stores text as positioned characters, not as paragraphs. The converter reads each page's text with its position, font and size, groups characters into lines and lines into paragraphs, detects headings from font size, and keeps bold and italic styling. Embedded images are extracted in reading order and each PDF page becomes its own section with the original page size.",
          "The result is a normal .docx file you can edit in Microsoft Word, Google Docs, LibreOffice or Pages.",
        ],
      },
      {
        heading: "What converts perfectly and what needs tidying",
        body: [
          "Letters, reports, contracts, articles and CVs convert very well. Complex layouts such as magazines with many columns flow in reading order, and tables are converted as lines of text, so expect some light tidying in Word for those.",
          "Scanned PDFs are pictures of text. Run OCR PDF first so the text can be recognised, then convert.",
        ],
      },
    ],
    tips: ["If your PDF is a scan, run OCR PDF first.", "Use Edit PDF instead if you only need to change a few words. It's quicker than converting back and forth."],
    useCases: [
      { who: "Office workers", what: "Edit a contract or report when you only have the PDF." },
      { who: "Students", what: "Reuse text from PDF readings in essays (with citations)." },
      { who: "Job seekers", what: "Update an old CV that only exists as a PDF." },
    ],
    faq: [
      { q: "How do I convert a PDF to Word for free?", a: "Drop your PDF onto PDFella's PDF to Word converter. It converts automatically in your browser; click Download to save the .docx. No account is needed." },
      { q: "Is my PDF uploaded to a server?", a: "No. PDF to Word conversion runs entirely in your browser." },
      { q: "How long does it take?", a: "Most documents convert in a few seconds. A live percentage shows progress for every page." },
      { q: "Will the formatting be kept?", a: "Headings, bold and italic text, font sizes, alignment, images and page sizes are kept. Tables become text lines and multi-column layouts flow in reading order." },
      { q: "Can I convert a scanned PDF to Word?", a: "Scanned pages are images, so run OCR PDF first to recognise the text, then convert." },
      { q: "Which Word format do I get?", a: "A .docx file that opens in Microsoft Word, Google Docs, LibreOffice and Pages." },
      { q: "Is there a file size limit?", a: "You can convert PDFs up to 100 MB." },
    ],
  },
  {
    slug: "pdf-to-jpg",
    keyword: "pdf to jpg",
    keywords: ["pdf to jpg converter", "convert pdf to jpg", "pdf to image", "pdf to jpeg", "save pdf as jpg"],
    metaTitle: "PDF to JPG Converter Free: Convert PDF to Images | PDFella",
    metaDescription: "Convert PDF to JPG online for free. Turn every page into a high-quality JPG image at the resolution you choose. Runs in your browser, no sign-up.",
    h1: "PDF to JPG converter",
    subtitle: "Turn every page of a PDF into a high-quality JPG image, at the resolution you choose.",
    quickAnswer: "To convert PDF to JPG, open PDFella's PDF to JPG converter, upload your PDF, choose a resolution (150 DPI is standard, 300 DPI for print) and optionally a page range, then click Convert to JPG. Download a single image or a ZIP with one JPG per page.",
    howToTitle: "How to convert PDF to JPG",
    totalTime: "PT1M",
    steps: [
      UPLOAD("PDF"),
      { title: "Choose resolution and pages", body: "Pick 72 DPI for screens, 150 DPI for most uses, 220 DPI for high quality or 300 DPI for print. Leave Pages empty for all pages or enter a range.", shot: 2 },
      { title: "Click Convert to JPG", body: "Each page is rendered to a JPG with live progress." },
      RESULT("images"),
    ],
    benefits: [
      { title: "Up to 300 DPI", body: "Print-quality images when you need them." },
      { title: "Choose pages", body: "Convert all pages or just a range." },
      PRIVATE,
      { title: "ZIP for many pages", body: "Multiple pages download together in one ZIP." },
    ],
    sections: [
      { heading: "Which resolution should I choose?", body: ["150 DPI is a good balance for sharing and presentations. Use 72 DPI for small web images, and 220–300 DPI when you need to print or zoom in on detail. Higher resolutions produce larger files."] },
      { heading: "JPG or PNG?", body: ["JPG files are smaller and ideal for photos and scanned pages. Choose PDF to PNG for lossless images with sharp text and graphics, such as diagrams or screenshots."] },
    ],
    tips: ["Use PDF to PNG for documents with lots of small text or line art."],
    useCases: [
      { who: "Social media managers", what: "Share a PDF page as an image on social platforms." },
      { who: "Presenters", what: "Drop PDF pages into slides as pictures." },
      { who: "Web editors", what: "Create preview images of documents." },
    ],
    faq: [
      { q: "How do I convert a PDF to JPG for free?", a: "Upload the PDF to PDF to JPG, choose a resolution and click Convert to JPG. Download the image or ZIP. No account needed." },
      { q: "Can I convert only some pages?", a: "Yes. Enter a page range such as 1-3." },
      { q: "What resolution are the images?", a: "Choose 72, 150, 220 or 300 DPI." },
      { q: "Is my PDF uploaded?", a: "No. Pages are rendered in your browser." },
      { q: "How do I get all pages?", a: "Multiple pages download as a ZIP with one JPG per page." },
      { q: "Is there a watermark?", a: "No." },
    ],
  },
  {
    slug: "pdf-to-png",
    keyword: "pdf to png",
    keywords: ["pdf to png converter", "convert pdf to png", "pdf to transparent png", "pdf page to png"],
    metaTitle: "PDF to PNG Converter Free: Lossless Page Images | PDFella",
    metaDescription: "Convert PDF pages to lossless PNG images online. Choose resolution and pages, download one PNG or a ZIP. Free, private, no sign-up.",
    h1: "PDF to PNG converter",
    subtitle: "Lossless PNG images of every page, perfect for sharp text, diagrams and screenshots.",
    quickAnswer: "To convert PDF to PNG, open PDFella's PDF to PNG converter, upload your PDF, choose a resolution and page range, and click Convert to PNG. Download a single PNG or a ZIP with one lossless PNG image per page.",
    howToTitle: "How to convert PDF to PNG",
    totalTime: "PT1M",
    steps: [UPLOAD("PDF"), { title: "Choose resolution and pages", body: "Pick a DPI from 72 to 300 and optionally a page range.", shot: 2 }, { title: "Click Convert to PNG", body: "Pages are rendered as lossless PNG images." }, RESULT("PNG images")],
    benefits: [{ title: "Lossless quality", body: "No compression artefacts around text and lines." }, { title: "Up to 300 DPI", body: "Sharp enough for print." }, PRIVATE, FREE],
    sections: [{ heading: "When to choose PNG over JPG", body: ["PNG keeps every pixel exactly, so text, charts and line drawings stay crisp. JPG makes smaller files and suits photos. For scanned documents JPG is usually enough; for digital documents with text, PNG looks sharper."] }],
    tips: ["PNG files are larger than JPG; use 150 DPI unless you need more detail."],
    useCases: [
      { who: "Designers", what: "Export artwork pages without quality loss." },
      { who: "Documentation writers", what: "Turn diagrams into images for wikis." },
      { who: "Teachers", what: "Use worksheet pages in slides and LMS posts." },
    ],
    faq: [
      { q: "Is PDF to PNG lossless?", a: "Yes. PNG is a lossless format, so pages are saved without compression artefacts." },
      { q: "Can I convert only one page?", a: "Yes. Enter that page number in Pages." },
      { q: "Is my file uploaded?", a: "No. Conversion runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "What background do the images have?", a: "Pages are rendered on white, like a printed page." },
      { q: "How do I download many pages?", a: "Multiple pages download as a ZIP." },
    ],
  },
  {
    slug: "pdf-to-excel",
    keyword: "pdf to excel",
    keywords: ["pdf to excel converter", "convert pdf to excel", "pdf to xlsx", "extract tables from pdf"],
    metaTitle: "PDF to Excel Converter: Convert PDF Tables to XLSX | PDFella",
    metaDescription: "Convert PDF to Excel online. Extract tables from PDF pages into an XLSX spreadsheet, one sheet per page, with numbers kept as numbers. Free, no sign-up.",
    h1: "PDF to Excel converter",
    subtitle: "Extract tables from a PDF into an Excel spreadsheet, one sheet per page.",
    quickAnswer: "To convert PDF to Excel, open PDFella's PDF to Excel converter, upload your PDF and click PDF to Excel. Tables on each page are detected and written to an XLSX workbook with one sheet per page. Download the spreadsheet when it's ready.",
    howToTitle: "How to convert PDF to Excel",
    totalTime: "PT1M",
    steps: [UPLOAD("PDF", false), { title: "Convert", body: "Click PDF to Excel. Upload and processing progress are shown as a percentage.", shot: 2 }, RESULT("Excel spreadsheet")],
    benefits: [{ title: "Table detection", body: "Ruled and aligned tables are detected on each page." }, { title: "Numbers stay numbers", body: "Values like 1,250.00 become numbers you can sum." }, { title: "One sheet per page", body: "Easy to find each page's data." }, CLOUD],
    sections: [{ heading: "Getting the best results", body: ["PDFs that were exported from Excel or accounting software convert best because their tables contain real text. Scanned statements need OCR PDF first. If a page has no ruled table, its text lines are split into columns where there are wide gaps."] }],
    tips: ["Run OCR PDF first for scanned bank statements or invoices."],
    useCases: [
      { who: "Accountants", what: "Turn PDF bank statements into spreadsheets." },
      { who: "Analysts", what: "Extract tables from reports for analysis." },
      { who: "Small businesses", what: "Move supplier price lists into Excel." },
    ],
    faq: [
      { q: "How do I convert a PDF to Excel?", a: "Upload the PDF to PDF to Excel and click PDF to Excel. Download the XLSX when it's ready." },
      { q: "Is my file uploaded?", a: "Yes, this tool uses secure cloud processing. Files are deleted automatically after conversion, within 60 minutes at most." },
      { q: "Will numbers be editable?", a: "Yes. Numeric values are written as numbers." },
      { q: "Can it convert scanned PDFs?", a: "Run OCR PDF first, then convert." },
      { q: "Is it free?", a: "Yes, within a generous daily allowance for cloud tools." },
      { q: "What if my PDF has no tables?", a: "Text lines are split into columns at wide gaps, one row per line." },
    ],
  },
  {
    slug: "pdf-to-powerpoint",
    keyword: "pdf to powerpoint",
    keywords: ["pdf to ppt", "pdf to pptx", "convert pdf to powerpoint", "pdf to slides"],
    metaTitle: "PDF to PowerPoint Converter: PDF to PPTX Online | PDFella",
    metaDescription: "Convert PDF to PowerPoint online. Each PDF page becomes a slide, with the page text in the speaker notes. Free, secure, no sign-up.",
    h1: "PDF to PowerPoint converter",
    subtitle: "Turn each page of a PDF into a PowerPoint slide, with the page text in the speaker notes.",
    quickAnswer: "To convert PDF to PowerPoint, open PDFella's PDF to PowerPoint converter, upload the PDF and click PDF to PowerPoint. Each page becomes a slide sized to the page, with its text in the speaker notes. Download the .pptx file.",
    howToTitle: "How to convert PDF to PowerPoint",
    totalTime: "PT1M",
    steps: [UPLOAD("PDF", false), { title: "Convert", body: "Click PDF to PowerPoint and watch the progress.", shot: 2 }, RESULT("PowerPoint file")],
    benefits: [{ title: "Faithful slides", body: "Each slide shows the page exactly as it looks." }, { title: "Text in notes", body: "Page text is copied into speaker notes for reference." }, { title: "Slide size matches", body: "Slides use the PDF page proportions." }, CLOUD],
    sections: [{ heading: "Presenting a PDF in PowerPoint", body: ["Converting is handy when you need to present a PDF alongside other slides, add transitions or speaker notes. Slides contain an image of each page, so the layout is exact; to edit the words, convert to Word or edit the PDF instead."] }],
    tips: ["Use Edit PDF to change text before converting."],
    useCases: [
      { who: "Presenters", what: "Present a PDF report in a meeting." },
      { who: "Teachers", what: "Turn handouts into lesson slides." },
      { who: "Sales teams", what: "Drop a PDF brochure into a pitch deck." },
    ],
    faq: [
      { q: "Can I edit the text on the slides?", a: "Slides show an image of each page with the text in the speaker notes. To edit wording, convert to Word or edit the PDF first." },
      { q: "Is my file uploaded?", a: "Yes, to secure temporary storage, and deleted automatically after conversion." },
      { q: "Is it free?", a: "Yes, within the daily allowance for cloud tools." },
      { q: "Which format do I get?", a: "A .pptx file that opens in PowerPoint, Keynote and Google Slides." },
      { q: "Does each page become one slide?", a: "Yes." },
      { q: "Is there a size limit?", a: "PDFs up to 100 MB." },
    ],
  },
  {
    slug: "pdf-to-text",
    keyword: "pdf to text",
    keywords: ["pdf to txt", "extract text from pdf", "copy text from pdf", "pdf text extractor"],
    metaTitle: "PDF to Text Converter: Extract Text from PDF Free | PDFella",
    metaDescription: "Extract all text from a PDF into a plain .txt file, page by page, in reading order. Free, private, runs in your browser, no sign-up.",
    h1: "PDF to text",
    subtitle: "Extract all of a PDF's text into a plain .txt file, page by page.",
    quickAnswer: "To extract text from a PDF, open PDFella's PDF to Text tool, upload the PDF and click Extract text. The text of every page is saved in reading order to a plain .txt file with page separators, ready to download.",
    howToTitle: "How to extract text from a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD("PDF"), { title: "Click Extract text", body: "Text is read from every page in reading order.", shot: 2 }, RESULT("text file")],
    benefits: [{ title: "Reading order", body: "Lines are kept in the order you'd read them." }, { title: "Page separators", body: "Each page is clearly marked." }, PRIVATE, FREE],
    sections: [{ heading: "No text found?", body: ["If the result is empty, your PDF is probably a scan, which means pictures of text. Run OCR PDF to recognise the text, then extract it."] }],
    tips: ["For formatted text, use PDF to Word instead."],
    useCases: [
      { who: "Researchers", what: "Analyse document text in other tools." },
      { who: "Developers", what: "Feed PDF content into scripts and search." },
      { who: "Writers", what: "Quote passages without retyping." },
    ],
    faq: [
      { q: "How do I copy all text from a PDF?", a: "Upload it to PDF to Text and click Extract text, then download the .txt file." },
      { q: "Why is my text file empty?", a: "The PDF is probably scanned. Run OCR PDF first." },
      { q: "Is my file uploaded?", a: "No. Extraction runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Is formatting kept?", a: "No. A .txt file is plain text. Use PDF to Word to keep formatting." },
      { q: "Which encoding is used?", a: "UTF-8, so every language is supported." },
    ],
  },
  {
    slug: "word-to-pdf",
    keyword: "word to pdf",
    keywords: ["doc to pdf converter", "word to pdf converter", "convert word to pdf", "docx to pdf", "doc to pdf"],
    metaTitle: "Word to PDF Converter Free: DOC & DOCX to PDF | PDFella",
    metaDescription: "Convert Word to PDF online for free. DOC, DOCX, ODT and text files become clean PDFs with layout, fonts and page breaks kept. Secure, no sign-up.",
    h1: "Word to PDF converter",
    subtitle: "Convert Word documents (DOCX, DOC, ODT) and text files into clean, professional PDFs.",
    quickAnswer: "To convert Word to PDF, open PDFella's Word to PDF converter, upload your DOCX, DOC or ODT file and click Word to PDF. The document is converted with its layout, fonts and page breaks, and the PDF is ready to download in seconds.",
    howToTitle: "How to convert Word to PDF",
    totalTime: "PT1M",
    steps: [UPLOAD("Word document", false), { title: "Click Word to PDF", body: "Upload and conversion progress are shown as a percentage.", shot: 2 }, RESULT("PDF")],
    benefits: [{ title: "Layout kept", body: "Fonts, images, tables, headers and page breaks." }, { title: "Many formats", body: "DOCX, DOC-compatible DOCX, ODT and TXT." }, { title: "Edit afterwards", body: "Open the PDF in the editor to sign or annotate it." }, CLOUD],
    sections: [{ heading: "Why convert Word to PDF?", body: ["A PDF looks the same on every device and can't be accidentally edited, which makes it the standard for CVs, contracts, invoices and forms. Converting also embeds fonts so your document looks right even if the reader doesn't have them."] }],
    tips: ["Sign the converted PDF straight away with Open in editor → Sign."],
    useCases: [
      { who: "Job seekers", what: "Send a CV that looks the same everywhere." },
      { who: "Businesses", what: "Turn invoices and quotes into PDFs." },
      { who: "Students", what: "Submit assignments in the required PDF format." },
    ],
    faq: [
      { q: "How do I convert Word to PDF for free?", a: "Upload your DOCX to Word to PDF and click Word to PDF, then download. No account is needed." },
      { q: "Is my document uploaded?", a: "Yes, to secure temporary storage for conversion, and it's deleted automatically afterwards (within 60 minutes at most)." },
      { q: "Will my fonts and layout be kept?", a: "Yes. Fonts, images, tables and page breaks are preserved." },
      { q: "Can I convert Excel or PowerPoint too?", a: "Yes. Use Excel to PDF or PowerPoint to PDF." },
      { q: "Is there a size limit?", a: "Files up to 100 MB." },
      { q: "Is there a watermark?", a: "No." },
    ],
  },
  {
    slug: "excel-to-pdf",
    keyword: "excel to pdf",
    keywords: ["xlsx to pdf", "convert excel to pdf", "excel to pdf converter", "spreadsheet to pdf"],
    metaTitle: "Excel to PDF Converter Free: XLSX to PDF Online | PDFella",
    metaDescription: "Convert Excel spreadsheets to PDF online. XLSX and ODS files become PDFs with formatting and every sheet included. Free, secure, no sign-up.",
    h1: "Excel to PDF converter",
    subtitle: "Turn Excel spreadsheets into PDFs that keep their formatting and include every sheet.",
    quickAnswer: "To convert Excel to PDF, open PDFella's Excel to PDF converter, upload your XLSX or ODS file and click Excel to PDF. Every sheet is converted with its formatting, and the PDF is ready to download in seconds.",
    howToTitle: "How to convert Excel to PDF",
    totalTime: "PT1M",
    steps: [UPLOAD("spreadsheet", false), { title: "Click Excel to PDF", body: "Progress is shown as a percentage while the workbook is converted.", shot: 2 }, RESULT("PDF")],
    benefits: [{ title: "Every sheet", body: "All sheets in the workbook are included." }, { title: "Formatting kept", body: "Fonts, colours, borders and number formats." }, { title: "Shareable", body: "PDFs look the same on every device." }, CLOUD],
    sections: [{ heading: "Tips for tidy spreadsheet PDFs", body: ["Set the print area and page orientation in Excel before converting. Wide sheets look best in landscape, and a defined print area avoids empty pages."] }],
    tips: ["Set landscape orientation in Excel for wide tables."],
    useCases: [
      { who: "Accountants", what: "Share financial statements as PDFs." },
      { who: "Project managers", what: "Send schedules and budgets." },
      { who: "Teachers", what: "Distribute grade sheets." },
    ],
    faq: [
      { q: "How do I convert Excel to PDF?", a: "Upload the XLSX to Excel to PDF, click Excel to PDF and download." },
      { q: "Are all sheets included?", a: "Yes." },
      { q: "Is my file uploaded?", a: "Yes, to secure temporary storage, and deleted automatically after conversion." },
      { q: "Is it free?", a: "Yes, within the daily allowance for cloud tools." },
      { q: "Can I convert PDF back to Excel?", a: "Yes, with PDF to Excel." },
      { q: "Is there a watermark?", a: "No." },
    ],
  },
  {
    slug: "powerpoint-to-pdf",
    keyword: "powerpoint to pdf",
    keywords: ["ppt to pdf", "pptx to pdf", "convert powerpoint to pdf", "slides to pdf"],
    metaTitle: "PowerPoint to PDF Converter Free: PPTX to PDF | PDFella",
    metaDescription: "Convert PowerPoint presentations to PDF online, one slide per page, with images and fonts kept. Free, secure, no sign-up.",
    h1: "PowerPoint to PDF converter",
    subtitle: "Turn presentations into PDFs, one slide per page, with images and fonts kept.",
    quickAnswer: "To convert PowerPoint to PDF, open PDFella's PowerPoint to PDF converter, upload your PPTX or ODP file and click PowerPoint to PDF. Each slide becomes one PDF page with its images and fonts, ready to download in seconds.",
    howToTitle: "How to convert PowerPoint to PDF",
    totalTime: "PT1M",
    steps: [UPLOAD("presentation", false), { title: "Click PowerPoint to PDF", body: "Progress is shown as a percentage.", shot: 2 }, RESULT("PDF")],
    benefits: [{ title: "One slide per page", body: "A clean handout of your deck." }, { title: "Fonts & images kept", body: "Your slides look exactly as designed." }, { title: "Easy to share", body: "Smaller and more universal than PPTX." }, CLOUD],
    sections: [{ heading: "Sharing presentations as PDFs", body: ["A PDF opens on any device without PowerPoint and can't be accidentally changed, which makes it ideal for sending decks to clients or posting handouts. Use Compress PDF afterwards if the file is large."] }],
    tips: ["Compress the PDF afterwards to make it easier to email."],
    useCases: [
      { who: "Sales teams", what: "Send pitch decks clients can open anywhere." },
      { who: "Speakers", what: "Share handouts after a talk." },
      { who: "Students", what: "Submit presentations as PDFs." },
    ],
    faq: [
      { q: "How do I convert PowerPoint to PDF?", a: "Upload the PPTX to PowerPoint to PDF, click PowerPoint to PDF and download." },
      { q: "Will animations be kept?", a: "No. A PDF is static; each slide is saved as it appears at the end of its animations." },
      { q: "Is my file uploaded?", a: "Yes, to secure temporary storage, and deleted automatically after conversion." },
      { q: "Is it free?", a: "Yes, within the daily allowance for cloud tools." },
      { q: "Are speaker notes included?", a: "No. Each page shows one slide." },
      { q: "Is there a watermark?", a: "No." },
    ],
  },
  {
    slug: "jpg-to-pdf",
    keyword: "jpg to pdf",
    keywords: ["jpg to pdf converter", "image to pdf", "convert jpg to pdf", "photo to pdf", "jpeg to pdf", "pictures to pdf"],
    metaTitle: "JPG to PDF Converter Free: Images to PDF Online | PDFella",
    metaDescription: "Convert JPG to PDF online for free. Combine photos into one PDF, reorder them, and choose A4, Letter or original size. Runs in your browser, no sign-up.",
    h1: "JPG to PDF converter",
    subtitle: "Combine JPG, PNG and WEBP images into one PDF, in any order, with A4, Letter or original page sizes.",
    quickAnswer: "To convert JPG to PDF, open PDFella's JPG to PDF converter, add one or more images, drag them into order, choose a page size (A4, Letter or the image size), orientation and margin, then click Convert to PDF and download. It all runs in your browser.",
    howToTitle: "How to convert JPG to PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD("images"),
      { title: "Arrange and set the page size", body: "Reorder images with the arrows, remove any you don't want, and add more. Choose A4, US Letter or Same as image, an orientation and a margin.", shot: 2 },
      { title: "Click Convert to PDF", body: "Every image becomes a page, centred and scaled to fit." },
      RESULT("PDF"),
    ],
    benefits: [
      { title: "Many images, one PDF", body: "Combine up to 20 images at once." },
      { title: "Page size options", body: "A4, Letter or the original image size, with margins." },
      PRIVATE,
      { title: "Original quality", body: "JPG and PNG images are embedded without recompression." },
    ],
    sections: [
      { heading: "Turning phone photos into a PDF", body: ["Photograph each page in good light, then add the photos here in order. Choose A4 or Letter with a small margin for a document that prints like a scan. If photos come out sideways, open the PDF in the editor and rotate those pages."] },
      { heading: "Supported image formats", body: ["JPG, PNG and WEBP. Transparent PNGs are placed on a white page."] },
    ],
    tips: ["Choose Automatic orientation so landscape photos get landscape pages.", "Compress the PDF afterwards if you need a smaller file for uploading."],
    useCases: [
      { who: "Students", what: "Submit photos of handwritten homework as one PDF." },
      { who: "Applicants", what: "Turn photos of ID and certificates into a single PDF." },
      { who: "Freelancers", what: "Combine receipts into an expenses PDF." },
    ],
    faq: [
      { q: "How do I convert JPG to PDF for free?", a: "Add your images to JPG to PDF, arrange them, choose a page size and click Convert to PDF. No account is needed." },
      { q: "Can I combine multiple JPGs into one PDF?", a: "Yes. Add up to 20 images and they become one PDF, one image per page." },
      { q: "Are my photos uploaded?", a: "No. Conversion happens in your browser." },
      { q: "Can I convert PNG or WEBP?", a: "Yes. JPG, PNG and WEBP are supported." },
      { q: "Will image quality be reduced?", a: "No. JPG and PNG images are embedded as they are." },
      { q: "Can I do this on my phone?", a: "Yes. It works in iPhone and Android browsers." },
    ],
  },
  {
    slug: "png-to-pdf",
    keyword: "png to pdf",
    keywords: ["convert png to pdf", "png to pdf converter", "image to pdf", "screenshot to pdf"],
    metaTitle: "PNG to PDF Converter Free: Convert Images to PDF | PDFella",
    metaDescription: "Convert PNG images to PDF online. Combine screenshots and graphics into one PDF with A4, Letter or original sizes. Free, private, no sign-up.",
    h1: "PNG to PDF converter",
    subtitle: "Combine PNG screenshots and graphics into a single PDF, losslessly.",
    quickAnswer: "To convert PNG to PDF, open PDFella's PNG to PDF converter, add your PNG images, arrange them, choose a page size and margin, and click Convert to PDF. The images are embedded losslessly and the PDF downloads straight from your browser.",
    howToTitle: "How to convert PNG to PDF",
    totalTime: "PT1M",
    steps: [UPLOAD("PNG images"), { title: "Arrange and set the page size", body: "Order the images and choose A4, Letter or Same as image.", shot: 2 }, { title: "Click Convert to PDF", body: "Each PNG becomes a page." }, RESULT("PDF")],
    benefits: [{ title: "Lossless", body: "PNGs are embedded without quality loss." }, { title: "Transparency handled", body: "Transparent areas appear on a white page." }, PRIVATE, FREE],
    sections: [{ heading: "Saving screenshots as a PDF", body: ["Collect screenshots, add them here in order and choose Same as image for pages that match each screenshot exactly. It's a quick way to document a process or report a bug."] }],
    tips: ["Use Same as image to avoid white borders around screenshots."],
    useCases: [
      { who: "Support teams", what: "Bundle screenshots into a report." },
      { who: "Designers", what: "Share mockups as a single PDF." },
      { who: "Students", what: "Combine diagrams into one file." },
    ],
    faq: [
      { q: "How do I convert PNG to PDF?", a: "Add PNGs to PNG to PDF, arrange them and click Convert to PDF." },
      { q: "Is quality reduced?", a: "No. PNGs are embedded losslessly." },
      { q: "Are my images uploaded?", a: "No. Conversion runs in your browser." },
      { q: "Can I mix PNG and JPG?", a: "Yes. JPG, PNG and WEBP can be combined." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "What happens to transparent areas?", a: "They're shown on a white page." },
    ],
  },
];
