import type { ToolContent } from "./types";

const UPLOAD_STEP = (what = "PDF") => ({
  title: `Upload your ${what}`,
  body: `Drag your ${what} onto the upload area, or click Upload document and choose it from your computer or phone. It opens instantly in the editor. No account and no installation needed.`,
  shot: 1,
});

export const editContent: ToolContent[] = [
  {
    slug: "edit-pdf",
    keyword: "edit pdf",
    keywords: ["pdf editor", "online pdf editor", "edit pdf online", "free pdf editor", "edit pdf text", "pdf editor online free"],
    metaTitle: "Edit PDF Online Free: PDF Editor, No Sign-Up | PDFella",
    metaDescription: "Edit PDF files online for free. Change existing text, add text, images, shapes and signatures, then download a real PDF. No sign-up, works in your browser.",
    h1: "Edit PDF online, free",
    subtitle: "A free online PDF editor that changes the text already in your PDF, not just what sits on top. Add text, images, shapes and signatures, then download a clean PDF.",
    quickAnswer: "To edit a PDF online, upload it to PDFella's free PDF editor, double-click any sentence to change its text, use the toolbar to add text, images, shapes or a signature, then click Save changes and Download PDF. Editing runs in your browser, so the file is never uploaded.",
    howToTitle: "How to edit a PDF online",
    totalTime: "PT2M",
    steps: [
      UPLOAD_STEP(),
      { title: "Double-click the text you want to change", body: "With the Select tool active, hover over any line and double-click a word. The whole sentence opens for editing with that word selected. Type your new text and press Esc when you're done.", shot: 2 },
      { title: "Add anything else you need", body: "Use the tool bar on the left: Add text for new text boxes, Whiteout to cover content, Markup to highlight, Image and Sign for pictures and signatures, Shapes for arrows and boxes. Every change can be undone with Ctrl/⌘ + Z." },
      { title: "Save and download your PDF", body: "Click Save changes. Rename the file if you like, then click Download PDF. You can also download every page as PNG or JPG, or continue editing.", shot: 3 },
    ],
    benefits: [
      { title: "Real text editing", body: "The original words are removed from the PDF and replaced, so the edited text is searchable and selectable, not just painted over." },
      { title: "Private by default", body: "Your PDF is edited on your own device. It isn't uploaded to our servers, and nothing is kept after you close the tab." },
      { title: "Everything in one editor", body: "Text, whiteout, highlights, drawings, shapes, images, signatures, comments, links, form fields and page organising." },
      { title: "Free with no sign-up", body: "No account, no watermark, no trial. Open the editor and start working straight away on any device." },
    ],
    sections: [
      {
        heading: "Can you really edit the text in a PDF?",
        body: [
          "PDF was designed as a fixed-layout format, so many online PDF editors only let you place new text boxes on top of a page. PDFella's PDF editor goes further: when you double-click a sentence, it reads the original text, its position, font size and colour, and when you save, it deletes those original characters from the page and writes your new text in the same place.",
          "Because the replacement is real text, it stays searchable and copyable in any PDF reader. If a PDF stores its text in a way that can't be changed safely (for example inside an embedded graphic), the editor covers the original neatly and places your new text on top, so the page still looks right.",
        ],
      },
      {
        heading: "What can you do with the online PDF editor?",
        body: [
          "Beyond changing text you can add new text with any size, colour and alignment; cover content with whiteout; highlight, underline or strike through text; draw freehand; add rectangles, ellipses, arrows and cloud callouts; insert and crop images; sign with a typed, drawn or uploaded signature; add sticky-note comments, stamps and hyperlinks; create fillable form fields; and permanently redact sensitive information.",
          "The page sidebar lets you reorder, rotate, duplicate, delete and insert pages without leaving the editor, and auto-save keeps your work safe if you refresh by accident.",
        ],
      },
    ],
    tips: [
      "Press ? in the editor to see every keyboard shortcut.",
      "Use Ctrl/⌘ + F to find a word, then mark every match for redaction in one click.",
      "Password-protected PDFs open after you enter the password once; restriction-only PDFs open automatically.",
    ],
    useCases: [
      { who: "Freelancers and businesses", what: "Fix a typo in a contract, update prices in a quote or change dates in an invoice without the original Word file." },
      { who: "Students", what: "Fill in application forms, annotate reading material and add your name to coursework." },
      { who: "HR and admin teams", what: "Update policy documents, sign letters and add comments for colleagues." },
    ],
    faq: [
      { q: "Is this PDF editor really free?", a: "Yes. Editing, signing, annotating and downloading are free, with no account, no watermark and no trial period." },
      { q: "Can I edit the existing text in my PDF?", a: "Yes. Double-click any word or sentence with the Select tool and type. The original text is removed from the PDF and replaced at the same position, size and style." },
      { q: "Is my PDF uploaded to a server?", a: "No. The PDF editor runs entirely in your browser, so your document stays on your device." },
      { q: "Will the edited PDF have a watermark?", a: "No. Downloaded files are clean PDFs with no watermark or branding added." },
      { q: "Can I edit a password-protected PDF?", a: "Yes. If the PDF only restricts editing it opens automatically. If it needs a password to open, enter it once and the document becomes fully editable." },
      { q: "Does it work on iPhone, Android and Mac?", a: "Yes. The editor works in current versions of Chrome, Safari, Edge and Firefox on Windows, macOS, iOS and Android." },
      { q: "What is the maximum file size?", a: "You can open PDFs of up to 100 MB. Pages load as you scroll, so long documents stay fast." },
    ],
  },
  {
    slug: "add-text-to-pdf",
    keyword: "add text to pdf",
    keywords: ["type on pdf", "write on pdf", "insert text into pdf", "add text box to pdf"],
    metaTitle: "Add Text to PDF Online Free: Type on Any PDF | PDFella",
    metaDescription: "Add text to a PDF online in seconds. Type anywhere on the page and choose font, size, colour and alignment. Free, no sign-up, no watermark.",
    h1: "Add text to PDF",
    subtitle: "Type anywhere on a PDF, with full control over font, size, colour, alignment and background.",
    quickAnswer: "To add text to a PDF, open it in PDFella, choose Add text from the tool bar, click where you want the text and start typing. Adjust the font, size and colour in the side panel, then click Save changes and Download PDF.",
    howToTitle: "How to add text to a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Choose Add text and click on the page", body: "Select Add text (shortcut T) in the left tool bar, then click where the text should go. Drag instead of clicking to set the width of the text box. Start typing straight away.", shot: 2 },
      { title: "Style your text", body: "Use the panel on the right to pick Helvetica, Times or Courier, set the size, make it bold, italic or underlined, change the colour, add a background and adjust alignment, line height and letter spacing." },
      { title: "Save and download", body: "Click Save changes, then Download PDF. The text is written into the PDF as real, selectable text.", shot: 3 },
    ],
    benefits: [
      { title: "Real, selectable text", body: "Added text is written into the PDF as text, not an image, so it stays sharp and can be searched." },
      { title: "Full formatting", body: "Font, size, colour, background, bold, italic, underline, alignment, line height and letter spacing." },
      { title: "Move, resize, rotate", body: "Drag text boxes anywhere, resize them and rotate them to any angle." },
      { title: "Works with any PDF", body: "Scans, forms, contracts and protected PDFs. Restrictions are removed automatically." },
    ],
    sections: [
      { heading: "Typing on a PDF that isn't a form", body: ["Many PDFs look like forms but have no fillable fields. With Add text you can type on top of any blank line or box, and line up your answers precisely using the arrow keys to nudge the text box one point at a time (hold Shift for ten)."] },
      { heading: "Adding text vs. editing existing text", body: ["Add text creates a new text box. If you want to change words that are already in the PDF, use the Select tool and double-click the sentence instead: the original text is replaced rather than covered."] },
    ],
    tips: ["Hold Shift while nudging with the arrow keys to move text 10 points at a time.", "Copy a styled text box with Ctrl/⌘ + C and paste it on another page to keep the same formatting."],
    useCases: [
      { who: "Anyone filling paper forms", what: "Type answers onto PDFs that don't have fillable fields." },
      { who: "Teachers", what: "Add instructions or feedback to worksheets." },
      { who: "Small businesses", what: "Add a reference number or note to an invoice before sending it." },
    ],
    faq: [
      { q: "How do I type on a PDF for free?", a: "Open the PDF in PDFella, choose Add text, click on the page and type. Then save and download. It's free and needs no account." },
      { q: "Can I change the font of added text?", a: "Yes. Choose Helvetica (Arial), Times or Courier, set any size, and make text bold, italic or underlined." },
      { q: "Will the text be searchable?", a: "Yes. Text is written into the PDF as real text, so it can be searched and selected." },
      { q: "Can I add text in other languages?", a: "Yes. Latin-script text is written as real text; other scripts such as Devanagari or Chinese are added as a high-resolution image so they display correctly." },
      { q: "Is my file uploaded?", a: "No. Adding text happens entirely in your browser." },
      { q: "Can I move the text after adding it?", a: "Yes. Select the text box to drag, resize or rotate it, or double-click it to change the words." },
    ],
  },
  {
    slug: "whiteout-pdf",
    keyword: "whiteout pdf",
    keywords: ["white out pdf", "cover text in pdf", "hide text in pdf", "erase text from pdf"],
    metaTitle: "Whiteout PDF Online: Cover & Erase Text Free | PDFella",
    metaDescription: "White out text or images in a PDF online. Drag to cover any area, match the page colour, and type over it. Free, private and no sign-up.",
    h1: "Whiteout PDF",
    subtitle: "Cover any part of a PDF with a clean box in white or any colour, then type over it if you need to.",
    quickAnswer: "To white out part of a PDF, open it in PDFella, choose Whiteout from the tool bar and drag a box over the content you want to hide. Change the cover colour if the page isn't white, add new text on top if needed, then save and download.",
    howToTitle: "How to white out text in a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Choose Whiteout and drag over the content", body: "Select Whiteout (shortcut W) and drag a rectangle over the text or image you want to hide. Click on a line of text to cover exactly that line.", shot: 2 },
      { title: "Match the colour and add text", body: "If your page has a tinted background, pick a matching cover colour in the side panel. Use Add text to type replacement text on top of the whiteout." },
      { title: "Save and download", body: "Click Save changes, then Download PDF.", shot: 3 },
    ],
    benefits: [
      { title: "Precise covering", body: "Drag any size of box, or click a line of text to cover exactly that line." },
      { title: "Any colour", body: "Match tinted or coloured page backgrounds so the cover is invisible." },
      { title: "Resize and move", body: "Adjust whiteout boxes at any time before saving." },
      { title: "Need it gone for good?", body: "Use Redact to remove content from the file, not just cover it." },
    ],
    sections: [
      { heading: "Whiteout vs. redaction: which should you use?", body: ["Whiteout is visual: it places a box over content, which is ideal for fixing mistakes or hiding something before printing. The covered content still exists inside the file.", "If the hidden information is sensitive, such as account numbers, personal data or confidential clauses, use Redact PDF instead. Redaction permanently deletes the underlying content so it can't be selected, searched or recovered."] },
      { heading: "Replacing text instead of covering it", body: ["To change wording, you usually don't need whiteout at all: double-click the sentence with the Select tool and type. The editor removes the original text and writes the new text in the same position."] },
    ],
    tips: ["Click directly on a line of text with the Whiteout tool to cover just that line.", "Use the eyedropper-like cover colour picker to match off-white scanned pages."],
    useCases: [
      { who: "Office workers", what: "Hide an outdated price or date before re-sending a document." },
      { who: "Teachers", what: "Create blank versions of worksheets by covering answers." },
      { who: "Anyone printing", what: "Remove notes or headers you don't want on paper." },
    ],
    faq: [
      { q: "Does whiteout delete the text underneath?", a: "No. Whiteout covers content visually. To delete sensitive content permanently, use Redact PDF." },
      { q: "Can I type over the whiteout?", a: "Yes. Add a text box with Add text on top of the whiteout box." },
      { q: "Can I use a colour other than white?", a: "Yes. Pick any cover colour to match the page background." },
      { q: "Is it free?", a: "Yes. Whiteout is free with no account and no watermark." },
      { q: "Is my file uploaded?", a: "No. The whiteout tool runs in your browser." },
      { q: "Can I undo a whiteout?", a: "Yes. Press Ctrl/⌘ + Z, or select the box and delete it, any time before you download." },
    ],
  },
  {
    slug: "highlight-pdf",
    keyword: "highlight pdf",
    keywords: ["highlight text in pdf", "pdf highlighter", "underline pdf", "strikethrough pdf"],
    metaTitle: "Highlight PDF Online Free: Highlight Text in a PDF | PDFella",
    metaDescription: "Highlight, underline or strike through text in any PDF online. Highlights snap to the lines you select. Free, private, no sign-up needed.",
    h1: "Highlight text in a PDF",
    subtitle: "Highlight, underline or strike through text. Markup snaps neatly to the lines you drag across.",
    quickAnswer: "To highlight text in a PDF, open it in PDFella, choose Markup then Highlight, and drag across the text. The highlight snaps to each line you cover. Pick a colour in the side panel, then save and download your highlighted PDF.",
    howToTitle: "How to highlight text in a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Choose Highlight from Markup", body: "Open the Markup group in the tool bar and pick Highlight (shortcut M). Underline and Strikethrough are in the same menu.", shot: 2 },
      { title: "Drag across the text", body: "Drag over the words you want to mark. The highlight snaps to each line of text, so it's always neat. Change colour and opacity in the side panel." },
      { title: "Save and download", body: "Click Save changes, then Download PDF. Highlights are kept in every PDF reader.", shot: 3 },
    ],
    benefits: [
      { title: "Snaps to text", body: "Highlights align to the lines you select instead of messy freehand boxes." },
      { title: "Six colours", body: "Yellow, blue, green, pink, orange and purple, plus adjustable opacity." },
      { title: "Underline & strike", body: "Mark corrections or emphasis with underline and strikethrough." },
      { title: "Readable output", body: "Highlights blend with the text underneath so nothing is hidden." },
    ],
    sections: [
      { heading: "Highlighting scanned PDFs", body: ["Snapping works on PDFs that contain real text. If your PDF is a scan, the highlight is drawn exactly where you drag. Run OCR PDF first to make the scan's text selectable and searchable."] },
      { heading: "Reviewing documents with colleagues", body: ["Combine highlights with sticky-note comments and stamps from the Annotate tools. Comments are saved as standard PDF annotations, so your colleagues see them in Acrobat, Preview or any other reader."] },
    ],
    tips: ["Use different colours for different meanings, for example yellow for key points and pink for questions.", "Search with Ctrl/⌘ + F to jump to every place a term appears."],
    useCases: [
      { who: "Students", what: "Mark key passages in readings and research papers." },
      { who: "Lawyers", what: "Highlight clauses that need attention during contract review." },
      { who: "Editors", what: "Strike through and underline changes in drafts." },
    ],
    faq: [
      { q: "How do I highlight text in a PDF for free?", a: "Open the PDF in PDFella, choose Markup → Highlight, drag across the text, then save and download." },
      { q: "Can I change the highlight colour?", a: "Yes. Choose from six colours and adjust the opacity." },
      { q: "Can I underline or strike through text?", a: "Yes. Underline and Strikethrough are in the same Markup menu." },
      { q: "Will highlights show in Adobe Acrobat?", a: "Yes. Highlights are written into the PDF and display in any PDF reader." },
      { q: "Is my PDF uploaded?", a: "No. Highlighting happens in your browser." },
      { q: "Can I remove a highlight?", a: "Yes. Select it and press Delete, or undo with Ctrl/⌘ + Z." },
    ],
  },
  {
    slug: "draw-on-pdf",
    keyword: "draw on pdf",
    keywords: ["pdf drawing tool", "freehand pdf", "draw lines on pdf", "draw arrows on pdf"],
    metaTitle: "Draw on PDF Online Free: Pen, Lines & Arrows | PDFella",
    metaDescription: "Draw on a PDF online with a freehand pen, lines and arrows. Works with a mouse, trackpad, stylus or finger. Free, private and no sign-up.",
    h1: "Draw on PDF",
    subtitle: "Freehand pen, straight lines and arrows, using a mouse, stylus or your finger.",
    quickAnswer: "To draw on a PDF, open it in PDFella, choose Draw → Pen and drag on the page to draw freehand. Use Shapes for straight lines and arrows, change colour and thickness in the side panel, then save and download the PDF.",
    howToTitle: "How to draw on a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Pick the Pen", body: "Open the Draw group and choose Pen (shortcut P). Set colour, stroke width and opacity in the side panel.", shot: 2 },
      { title: "Draw on the page", body: "Drag to draw. Strokes are smoothed automatically. Use the Eraser to remove drawings, or Shapes → Line / Arrow for straight lines (hold Shift to snap to 45°)." },
      { title: "Save and download", body: "Click Save changes, then Download PDF. Drawings are saved as crisp vector lines.", shot: 3 },
    ],
    benefits: [
      { title: "Smooth strokes", body: "Freehand lines are smoothed so handwriting and sketches look clean." },
      { title: "Vector output", body: "Drawings stay sharp at any zoom level and print perfectly." },
      { title: "Touch & stylus", body: "Draw with Apple Pencil, a stylus or your finger on tablets and phones." },
      { title: "Object eraser", body: "Remove whole strokes with one swipe of the eraser." },
    ],
    sections: [
      { heading: "Drawing with a tablet or phone", body: ["On touch devices the tool bar moves to the bottom of the screen and drawing follows your finger or stylus. Pinch to zoom in for detail."] },
      { heading: "Lines, arrows and shapes", body: ["For diagrams and callouts, the Shapes group adds straight lines, arrows, rectangles, ellipses, polygons and clouds, each with its own stroke and fill colour."] },
    ],
    tips: ["Hold Shift while drawing a line or arrow to snap it to 45° angles.", "Lower the opacity to sketch over text without hiding it."],
    useCases: [
      { who: "Designers", what: "Mark up proofs with sketches and arrows." },
      { who: "Teachers", what: "Correct homework by hand on a tablet." },
      { who: "Engineers", what: "Annotate drawings and plans during review." },
    ],
    faq: [
      { q: "Can I draw on a PDF with my finger?", a: "Yes. On phones and tablets the pen follows your finger or stylus." },
      { q: "How do I draw straight lines?", a: "Use Shapes → Line or Arrow and hold Shift to snap to 45°." },
      { q: "Can I erase drawings?", a: "Yes. Use the Eraser and swipe across strokes to remove them." },
      { q: "Is it free?", a: "Yes. Drawing on PDFs is free with no account." },
      { q: "Are drawings saved as images?", a: "No. They're saved as vector lines, so they stay sharp at any zoom." },
      { q: "Is my file uploaded?", a: "No. Everything happens in your browser." },
    ],
  },
  {
    slug: "annotate-pdf",
    keyword: "annotate pdf",
    keywords: ["pdf annotator", "comment on pdf", "add sticky notes to pdf", "pdf stamps", "mark up pdf"],
    metaTitle: "Annotate PDF Online Free: Comments, Notes & Stamps | PDFella",
    metaDescription: "Annotate PDFs online with sticky-note comments, stamps, checkmarks, shapes and links. Notes are saved as real PDF annotations. Free, no sign-up.",
    h1: "Annotate PDF online",
    subtitle: "Add sticky-note comments, approval stamps, checkmarks, shapes and hyperlinks. Comments are saved as real PDF annotations.",
    quickAnswer: "To annotate a PDF, open it in PDFella and use the tool bar: Comment adds sticky notes, Stamps adds Approved, Draft or Confidential stamps and checkmarks, Markup highlights text and Shapes adds arrows and boxes. Save changes and download. Comments open in any PDF reader.",
    howToTitle: "How to annotate a PDF",
    totalTime: "PT2M",
    steps: [
      UPLOAD_STEP(),
      { title: "Add comments and stamps", body: "Choose Comment and click where the note belongs, then type it in the side panel with your name. Open Stamps for Approved, Reviewed, Draft and Confidential stamps, checkmarks, crosses and stars.", shot: 2 },
      { title: "Mark up the content", body: "Use Markup to highlight or underline text, Shapes for arrows, boxes and cloud callouts, and Link to make an area clickable." },
      { title: "Save and share", body: "Click Save changes and Download PDF. Your colleagues can read the comments in Acrobat, Preview, Edge or any PDF viewer.", shot: 3 },
    ],
    benefits: [
      { title: "Standard PDF comments", body: "Sticky notes are saved as real PDF annotations that every reader understands." },
      { title: "Ten stamps", body: "Approved, Reviewed, Draft, Confidential, Final, Rejected, Paid, Received, Void and Copy." },
      { title: "Shapes & clouds", body: "Draw attention with arrows, ellipses, rectangles and revision clouds." },
      { title: "Clickable links", body: "Turn any area into a link to a website or email address." },
    ],
    sections: [
      { heading: "Reviewing a document with your team", body: ["A good review combines three things: highlights to show what you mean, comments to say why, and stamps to record the decision. PDFella keeps all three on the page and saves comments in the standard PDF format, so reviewers don't need any particular software."] },
      { heading: "Approving documents with stamps", body: ["Stamps are drawn as crisp vector graphics with a slight rotation, like a rubber stamp. Edit the stamp text to create your own label, such as 'Checked by AM'."] },
    ],
    tips: ["Edit a stamp's text to create custom labels.", "Use the Cloud shape for revision marks on drawings and plans."],
    useCases: [
      { who: "Managers", what: "Approve invoices and reports with a stamp and a comment." },
      { who: "Designers", what: "Mark up proofs with clouds, arrows and notes." },
      { who: "Legal teams", what: "Comment on contract clauses during negotiation." },
    ],
    faq: [
      { q: "Will my comments show in Adobe Acrobat?", a: "Yes. Sticky notes are saved as standard PDF text annotations." },
      { q: "Can I create custom stamps?", a: "Yes. Place a stamp and edit its text and colour." },
      { q: "Can I add hyperlinks to a PDF?", a: "Yes. Use the Link tool to make any area link to a web address or email." },
      { q: "Is annotating free?", a: "Yes. All annotation tools are free with no account." },
      { q: "Is my document uploaded?", a: "No. Annotation runs in your browser." },
      { q: "Can I annotate on a phone?", a: "Yes. The editor adapts to phones and tablets with a bottom tool bar." },
    ],
  },
  {
    slug: "add-image-to-pdf",
    keyword: "add image to pdf",
    keywords: ["insert image into pdf", "add picture to pdf", "add logo to pdf", "put image on pdf"],
    metaTitle: "Add Image to PDF Online Free: Insert JPG or PNG | PDFella",
    metaDescription: "Insert images into a PDF online. Add PNG, JPG or WEBP pictures and logos, then move, resize, crop and rotate them. Free and private.",
    h1: "Add an image to a PDF",
    subtitle: "Insert PNG, JPG or WEBP images and logos, then move, resize, crop and rotate them.",
    quickAnswer: "To add an image to a PDF, open the PDF in PDFella, choose Image in the tool bar, pick a PNG, JPG or WEBP file and click on the page to place it. Drag to move, use the corners to resize, crop in the side panel, then save and download.",
    howToTitle: "How to add an image to a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Choose Image and pick a picture", body: "Click Image (shortcut I) and choose a PNG, JPG or WEBP file from your device. Then click on the page where it should go.", shot: 2 },
      { title: "Position, crop and rotate", body: "Drag the image to move it and pull a corner to resize while keeping its proportions. Use the crop sliders and rotation in the side panel." },
      { title: "Save and download", body: "Click Save changes, then Download PDF.", shot: 3 },
    ],
    benefits: [
      { title: "PNG, JPG & WEBP", body: "Transparent PNG logos stay transparent on the page." },
      { title: "Crop & rotate", body: "Trim edges and rotate to any angle without another app." },
      { title: "Keeps proportions", body: "Corner handles resize without stretching." },
      { title: "Sharp output", body: "Images are embedded at high resolution." },
    ],
    sections: [
      { heading: "Adding a logo or letterhead", body: ["Use a transparent PNG for logos so they sit cleanly on the page. Place it on the first page, then copy and paste it onto other pages so it's in the same position each time."] },
      { heading: "Adding photos to reports", body: ["Large photos are resized to a sensible size automatically. If you need a whole page per image, Convert JPG to PDF and merge it in, or use Add pages in the page sidebar."] },
    ],
    tips: ["Copy (Ctrl/⌘ + C) and paste (Ctrl/⌘ + V) an image to repeat it across pages.", "Hold Shift while resizing to unlock the aspect ratio."],
    useCases: [
      { who: "Businesses", what: "Add a logo to quotes and invoices." },
      { who: "Estate agents", what: "Insert property photos into brochures." },
      { who: "Students", what: "Add diagrams to assignments." },
    ],
    faq: [
      { q: "Which image formats can I add?", a: "PNG, JPG and WEBP." },
      { q: "Can I crop the image?", a: "Yes. Use the crop sliders in the side panel." },
      { q: "Will transparency be kept?", a: "Yes. Transparent areas of PNG images stay transparent." },
      { q: "Is it free?", a: "Yes, with no account and no watermark." },
      { q: "Is my file uploaded?", a: "No. Everything happens in your browser." },
      { q: "Can I add an image as a new page?", a: "Yes. Use Add pages in the page sidebar to insert an image as its own page." },
    ],
  },
  {
    slug: "add-shapes-to-pdf",
    keyword: "add shapes to pdf",
    keywords: ["draw rectangle on pdf", "add arrow to pdf", "draw circle on pdf", "pdf shapes"],
    metaTitle: "Add Shapes to PDF Online: Boxes, Circles & Arrows | PDFella",
    metaDescription: "Add rectangles, circles, arrows, polygons and cloud shapes to a PDF online. Set stroke, fill and opacity. Free, private, no sign-up.",
    h1: "Add shapes to a PDF",
    subtitle: "Rectangles, ellipses, lines, arrows, polygons and revision clouds, with your own colours.",
    quickAnswer: "To add shapes to a PDF, open it in PDFella, open the Shapes menu and choose Rectangle, Ellipse, Line, Arrow, Polygon or Cloud, then drag on the page. Set stroke, fill and opacity in the side panel, then save and download.",
    howToTitle: "How to add shapes to a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Open Shapes and pick one", body: "Click Shapes in the tool bar and choose a rectangle, ellipse, line, arrow, polygon or cloud.", shot: 2 },
      { title: "Drag to draw and style it", body: "Drag on the page to draw. Hold Shift for perfect squares and circles. Set stroke colour, fill, thickness and opacity on the right." },
      { title: "Save and download", body: "Click Save changes, then Download PDF.", shot: 3 },
    ],
    benefits: [
      { title: "Six shape types", body: "Rectangle, ellipse, line, arrow, polygon and cloud." },
      { title: "Fill & stroke", body: "Any colours, thickness and transparency." },
      { title: "Rotate & resize", body: "Every shape can be moved, resized and rotated." },
      { title: "Vector quality", body: "Shapes stay crisp at every zoom level." },
    ],
    sections: [{ heading: "Using shapes for clear feedback", body: ["Boxes and circles draw the eye to a specific area, arrows connect a comment to what it refers to, and clouds are the standard way to mark revisions on drawings. Combine them with sticky-note comments for complete feedback."] }],
    tips: ["Hold Shift to draw perfect squares and circles.", "Set fill to none and reduce opacity to frame content without hiding it."],
    useCases: [
      { who: "Architects & engineers", what: "Mark revisions on plans with cloud shapes." },
      { who: "Teachers", what: "Circle mistakes and draw arrows to corrections." },
      { who: "Product teams", what: "Annotate screenshots and specs." },
    ],
    faq: [
      { q: "Can I draw a perfect circle?", a: "Yes. Choose Ellipse and hold Shift while dragging." },
      { q: "Can I fill a shape with colour?", a: "Yes. Choose any fill colour or none." },
      { q: "Can I rotate shapes?", a: "Yes. Use the rotate handle above a selected shape." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Is my file uploaded?", a: "No. Shapes are added in your browser." },
      { q: "Will shapes look sharp when printed?", a: "Yes. They're saved as vector graphics." },
    ],
  },
  {
    slug: "sign-pdf",
    keyword: "sign pdf",
    keywords: ["sign pdf online", "electronic signature pdf", "add signature to pdf", "e-sign pdf free", "sign pdf free"],
    metaTitle: "Sign PDF Online Free: Add Your Signature | PDFella",
    metaDescription: "Sign PDF documents online for free. Type, draw or upload your signature, place it anywhere, add the date and download. No account, nothing uploaded.",
    h1: "Sign PDF online, free",
    subtitle: "Type, draw or upload your signature, place it on any page, and download the signed PDF in seconds.",
    quickAnswer: "To sign a PDF online, open it in PDFella, choose Sign in the tool bar, then type your name, draw your signature or upload an image of it. Click on the page to place it, resize it to fit, then click Save changes and Download PDF.",
    howToTitle: "How to sign a PDF online",
    totalTime: "PT1M",
    steps: [
      UPLOAD_STEP(),
      { title: "Create your signature", body: "Click Sign (shortcut S). Type your name and choose a handwriting style, draw with your mouse, trackpad or finger, or upload a photo of your signature. The white background of uploaded signatures can be removed automatically.", shot: 2 },
      { title: "Place and size it", body: "Click on the signature line to place it. Drag to move it, use the corners to resize, and add a date with Add text. Your signature is remembered for the rest of the session so you can sign other pages quickly." },
      { title: "Download the signed PDF", body: "Click Save changes, then Download PDF.", shot: 3 },
    ],
    benefits: [
      { title: "Three ways to sign", body: "Typed in a handwriting font, drawn by hand, or uploaded from an image." },
      { title: "Never stored", body: "Signatures exist only in your browser tab and are never uploaded or saved." },
      { title: "Sign on any device", body: "Draw with your finger on a phone or a stylus on a tablet." },
      { title: "Add signature fields", body: "Create signature, date and initials fields for others with Create PDF Form." },
    ],
    sections: [
      { heading: "Is an electronic signature legally binding?", body: ["In many countries, including under the US ESIGN Act and the EU eIDAS regulation, a simple electronic signature like an image of your signature placed on a document can be legally valid when all parties agree to sign electronically. Some documents, such as certain property, court or notarised documents, may require a qualified or witnessed signature. If in doubt, check the requirements for your document and country."] },
      { heading: "Signing a PDF on your phone", body: ["Open the PDF from your phone's browser, choose Sign and draw your signature with your finger. The tool bar sits at the bottom of the screen so it's easy to reach with one hand."] },
    ],
    tips: ["Upload a photo of your signature on white paper and keep Remove white background switched on for a clean result.", "Use a dark blue ink colour so a printed copy looks hand-signed."],
    useCases: [
      { who: "Freelancers", what: "Sign contracts and NDAs from clients without printing." },
      { who: "Tenants and landlords", what: "Sign rental agreements and inventories." },
      { who: "HR", what: "Sign offer letters and policy acknowledgements." },
    ],
    faq: [
      { q: "How do I sign a PDF for free?", a: "Open the PDF in PDFella, choose Sign, type, draw or upload your signature, click to place it, then save and download. No account is needed." },
      { q: "Is my signature saved anywhere?", a: "No. It's kept only in your current browser tab and is never uploaded or stored." },
      { q: "Can I sign a PDF on my phone?", a: "Yes. Draw your signature with your finger in any mobile browser." },
      { q: "Can I add the date next to my signature?", a: "Yes. Use Add text to type the date anywhere on the page." },
      { q: "Is an electronic signature legal?", a: "Simple electronic signatures are accepted for many documents in many countries, but some documents need a qualified or witnessed signature. Check the requirements for your document." },
      { q: "Can I ask someone else to sign?", a: "You can add signature and date fields with Create PDF Form and send them the PDF. They can sign in any PDF reader or with PDFella." },
    ],
  },
];
