import type { ToolContent } from "./types";

const UPLOAD = (what = "your PDF") => ({ title: `Upload ${what}`, body: `Drag ${what} onto the upload area or click Choose file. It opens in your browser straight away. Nothing is uploaded to a server.`, shot: 1 });
const RESULT = { title: "Download the result", body: "Rename the file if you like and click Download. You can also open the result in the editor to keep working on it.", shot: 3 };

const PRIVATE = { title: "Runs in your browser", body: "Your files never leave your device, which keeps confidential documents private and makes processing fast." };
const FREE = { title: "Free, no account", body: "No sign-up, no watermark and no daily limit for browser-based tools." };

export const organiseContent: ToolContent[] = [
  {
    slug: "merge-pdf",
    keyword: "merge pdf",
    keywords: ["combine pdf", "pdf merge", "merge pdf files", "join pdf", "pdf merge online", "combine pdf files into one"],
    metaTitle: "Merge PDF Files Online Free: Combine PDFs | PDFella",
    metaDescription: "Merge PDF files online for free. Combine several PDFs into one document, drag to reorder, preview pages and download. Fast, private, no sign-up.",
    h1: "Merge PDF files",
    subtitle: "Combine multiple PDFs into one document in the order you choose, right in your browser.",
    quickAnswer: "To merge PDF files, open PDFella's Merge PDF tool, add two or more PDFs, drag them into the order you want and click Merge PDFs. Download the combined PDF. Merging runs in your browser, so your files are never uploaded.",
    howToTitle: "How to merge PDF files",
    totalTime: "PT1M",
    steps: [
      UPLOAD("the PDFs you want to combine"),
      { title: "Put the files in order", body: "Each file shows its first page, page count and size. Drag files to reorder them, use the arrows to move one up or down, remove any you don't need, or add more PDFs.", shot: 2 },
      { title: "Click Merge PDFs", body: "Your files are combined into a single PDF in the order shown, with every page kept exactly as it was." },
      RESULT,
    ],
    benefits: [
      { title: "Drag-and-drop order", body: "Preview each file and arrange them exactly how you want before merging." },
      PRIVATE,
      { title: "Keeps quality", body: "Pages are copied as they are, so text stays selectable and images aren't recompressed." },
      { title: "Protected PDFs welcome", body: "Restricted PDFs are unlocked automatically; password-protected ones ask for the password once." },
    ],
    sections: [
      { heading: "How to combine PDFs in a specific order", body: ["The order of the list is the order of the merged document. If you need to interleave pages from different files, merge them first, then open the result in the editor and drag page thumbnails into the exact order you want."] },
      { heading: "Merging PDFs with other file types", body: ["To merge images or Office files with PDFs, convert them first with JPG to PDF or Word to PDF, then merge. Or open a PDF in the editor and use Add pages to insert PDFs and images at any position."] },
    ],
    tips: ["Open the merged PDF in the editor to delete or rotate individual pages.", "Use Compress PDF afterwards if the combined file is too large to email."],
    useCases: [
      { who: "Job seekers", what: "Combine a CV, cover letter and certificates into one application PDF." },
      { who: "Accountants", what: "Merge monthly statements and receipts into a single file." },
      { who: "Students", what: "Join lecture notes or chapters into one document." },
    ],
    faq: [
      { q: "How do I merge PDF files for free?", a: "Open Merge PDF, add your files, drag them into order and click Merge PDFs. Then download the combined PDF. It's free with no account." },
      { q: "Is there a limit on how many PDFs I can merge?", a: "You can merge up to 20 files at once, each up to 100 MB." },
      { q: "Are my files uploaded?", a: "No. Merging happens entirely in your browser." },
      { q: "Can I change the order of the files?", a: "Yes. Drag the files or use the up and down arrows before merging." },
      { q: "Will the merged PDF lose quality?", a: "No. Pages are copied as they are, without recompression." },
      { q: "Can I merge password-protected PDFs?", a: "Yes. Enter the password once if the PDF requires one to open; restriction-only PDFs open automatically." },
      { q: "Can I merge PDFs on my phone?", a: "Yes. The tool works in mobile browsers on iPhone and Android." },
    ],
  },
  {
    slug: "split-pdf",
    keyword: "split pdf",
    keywords: ["split pdf pages", "separate pdf pages", "split pdf online", "divide pdf", "split pdf into multiple files"],
    metaTitle: "Split PDF Online Free: Separate PDF Pages | PDFella",
    metaDescription: "Split a PDF into separate files by page range, every page, a fixed number of pages, or odd and even pages. Free, private, no sign-up.",
    h1: "Split PDF",
    subtitle: "Divide one PDF into several files by page ranges, single pages, fixed chunks, or odd and even pages.",
    quickAnswer: "To split a PDF, open PDFella's Split PDF tool, upload the file, choose By range, Fixed size or Odd / even, enter the pages you want (for example 1-3, 4, 5-) and click Split PDF. Download a single PDF or a ZIP of all the parts.",
    howToTitle: "How to split a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Choose how to split", body: "Pick By range to type page ranges such as 1-3, 4, 5-; Fixed size to split every N pages (1 = every page separately); or Odd / even to separate odd and even pages. The tool shows how many files you'll get.", shot: 2 },
      { title: "Click Split PDF", body: "Each range becomes its own PDF. If there's more than one file, they're bundled into a ZIP." },
      RESULT,
    ],
    benefits: [
      { title: "Four ways to split", body: "Custom ranges, every page, fixed-size chunks or odd/even." },
      PRIVATE,
      { title: "Group ranges", body: "Use ; to put several ranges into one file, e.g. 1-2,5; 3-4." },
      FREE,
    ],
    sections: [
      { heading: "Splitting by page ranges", body: ["Separate ranges with commas to create one file per range: 1-3, 4, 5- creates three files (pages 1–3, page 4, and page 5 to the end). To combine non-adjacent pages into the same file, separate groups with semicolons: 1-2,5; 3-4."] },
      { heading: "Need only a few pages?", body: ["If you just want certain pages in one new PDF, Extract PDF Pages is quicker: click the thumbnails you want and download them as a single file."] },
    ],
    tips: ["Leave the end of a range open (e.g. 5-) to go to the last page.", "Use Fixed size = 1 to save every page as its own PDF."],
    useCases: [
      { who: "Office staff", what: "Split a scanned batch into separate letters or invoices." },
      { who: "Teachers", what: "Separate a workbook into individual worksheets." },
      { who: "Lawyers", what: "Extract exhibits from a long bundle." },
    ],
    faq: [
      { q: "How do I split a PDF into separate pages?", a: "Choose Fixed size and enter 1. Every page becomes its own PDF, downloaded together in a ZIP." },
      { q: "Can I split a PDF by page range?", a: "Yes. Choose By range and type ranges like 1-3, 4, 5-." },
      { q: "Are my files uploaded?", a: "No. Splitting runs entirely in your browser." },
      { q: "How do I get the split files?", a: "One file downloads directly; several files download as a ZIP." },
      { q: "Is splitting free?", a: "Yes, with no account or watermark." },
      { q: "Does splitting reduce quality?", a: "No. Pages are copied without recompression." },
    ],
  },
  {
    slug: "rotate-pdf",
    keyword: "rotate pdf",
    keywords: ["rotate pdf pages", "rotate pdf online", "turn pdf sideways", "fix upside down pdf", "rotate pdf and save"],
    metaTitle: "Rotate PDF Online Free: Rotate Pages & Save | PDFella",
    metaDescription: "Rotate PDF pages online and save them permanently. Turn single pages or the whole document left or right. Free, private, no sign-up.",
    h1: "Rotate PDF pages",
    subtitle: "Turn individual pages or the whole document and save the rotation permanently.",
    quickAnswer: "To rotate a PDF, open PDFella's Rotate PDF tool, upload the file, then use the rotate buttons on each page thumbnail or rotate all pages at once. Click Apply rotation and download. The new orientation is saved in the file, so it opens correctly everywhere.",
    howToTitle: "How to rotate PDF pages",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Rotate pages", body: "Hover over a thumbnail and click the left or right arrow to rotate that page. To rotate everything, use All left or All right. Select several pages first to rotate just those.", shot: 2 },
      { title: "Click Apply rotation", body: "The rotation is written into the PDF so it stays turned in every reader and when printed." },
      RESULT,
    ],
    benefits: [
      { title: "Per-page control", body: "Rotate one page, a selection, or all pages." },
      { title: "Saved permanently", body: "Unlike a viewer's rotate button, the orientation is stored in the file." },
      PRIVATE,
      FREE,
    ],
    sections: [{ heading: "Why does my PDF open sideways?", body: ["Scanners and phone cameras often save pages with the wrong orientation. Viewing apps can rotate the view, but that change usually isn't saved. Rotating with this tool updates each page's rotation inside the PDF, so it's fixed for everyone who opens it."] }],
    tips: ["Select several thumbnails first, then use the rotate buttons to turn only those pages."],
    useCases: [
      { who: "Anyone scanning", what: "Fix upside-down or sideways scanned pages." },
      { who: "Engineers", what: "Turn landscape drawings inside a portrait document." },
      { who: "Students", what: "Rotate photographed notes to read normally." },
    ],
    faq: [
      { q: "How do I rotate a PDF and save it?", a: "Rotate pages in Rotate PDF, click Apply rotation, then download. The rotation is saved in the file." },
      { q: "Can I rotate only one page?", a: "Yes. Use the rotate arrows on that page's thumbnail." },
      { q: "Is my file uploaded?", a: "No. Rotation happens in your browser." },
      { q: "Does rotating reduce quality?", a: "No. Only the page orientation changes." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Can I rotate pages inside the editor?", a: "Yes. Select pages in the editor's page sidebar and use the rotate buttons." },
    ],
  },
  {
    slug: "rearrange-pdf-pages",
    keyword: "rearrange pdf pages",
    keywords: ["reorder pdf pages", "organize pdf", "move pages in pdf", "change page order pdf", "sort pdf pages"],
    metaTitle: "Rearrange PDF Pages Online: Reorder & Organize | PDFella",
    metaDescription: "Rearrange PDF pages online with drag and drop. Reorder, duplicate, rotate, delete and add blank pages, then save. Free, private, no sign-up.",
    h1: "Rearrange PDF pages",
    subtitle: "Drag page thumbnails into a new order, duplicate, rotate or delete pages and add blank ones.",
    quickAnswer: "To rearrange PDF pages, open PDFella's Rearrange PDF Pages tool, upload the file and drag the page thumbnails into the order you want. Duplicate, rotate, delete or add blank pages as needed, then click Save new order and download the reorganised PDF.",
    howToTitle: "How to rearrange pages in a PDF",
    totalTime: "PT2M",
    steps: [
      UPLOAD(),
      { title: "Drag pages into order", body: "Every page appears as a thumbnail. Drag a page to its new position. With the keyboard, select a page and press Alt + ← / → to move it.", shot: 2 },
      { title: "Tidy up", body: "Select pages to Duplicate, Delete or Rotate them, or add a Blank page at the end." },
      { title: "Save new order and download", body: "Click Save new order, rename the file if you like, and download it.", shot: 3 },
    ],
    benefits: [
      { title: "Drag and drop", body: "Visual thumbnails make it easy to see exactly what you're moving." },
      { title: "Duplicate & blank pages", body: "Copy pages or insert blanks for notes and printing." },
      PRIVATE,
      { title: "Keyboard accessible", body: "Move pages with Alt + arrow keys without a mouse." },
    ],
    sections: [{ heading: "Organising a PDF inside the editor", body: ["The editor has the same page tools in its left sidebar, so you can reorder pages and edit their content in one session. Use Add pages there to insert pages from another PDF or an image."] }],
    tips: ["Add a blank page after a section to create space for handwritten notes when printing."],
    useCases: [
      { who: "Office teams", what: "Put scanned pages back in the right order." },
      { who: "Publishers", what: "Reorder chapters before sending a proof." },
      { who: "Students", what: "Arrange lecture slides by topic." },
    ],
    faq: [
      { q: "How do I change the order of pages in a PDF?", a: "Drag the page thumbnails into the order you want and click Save new order." },
      { q: "Can I duplicate a page?", a: "Yes. Select it and click Duplicate." },
      { q: "Can I add a blank page?", a: "Yes. Click Blank page to add one, then drag it into position." },
      { q: "Is my file uploaded?", a: "No. Everything happens in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Does it change the content of pages?", a: "No. Pages are moved as they are, without recompression." },
    ],
  },
  {
    slug: "delete-pdf-pages",
    keyword: "delete pdf pages",
    keywords: ["remove pages from pdf", "delete pages from pdf online", "remove page from pdf free"],
    metaTitle: "Delete PDF Pages Online Free: Remove Pages | PDFella",
    metaDescription: "Delete pages from a PDF online. Click the pages to remove, or type a range, and download a clean PDF. Free, private and no sign-up.",
    h1: "Delete pages from a PDF",
    subtitle: "Click the pages you don't need, or type a range, and download a PDF without them.",
    quickAnswer: "To delete pages from a PDF, open PDFella's Delete PDF Pages tool, upload the file and click each page you want to remove (or type a range like 2-4). Click Delete pages and download the new PDF. Removed pages are fully deleted from the file.",
    howToTitle: "How to delete pages from a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Select the pages to remove", body: "Click page thumbnails to mark them (they turn red), or type a range such as 2-4, 7 and click Select.", shot: 2 },
      { title: "Click Delete pages", body: "The selected pages are removed and their content is cleaned out of the file, not just hidden." },
      RESULT,
    ],
    benefits: [
      { title: "Click or type ranges", body: "Select pages visually or by number." },
      { title: "Really removed", body: "Deleted pages and their content are stripped from the file." },
      PRIVATE,
      FREE,
    ],
    sections: [{ heading: "Are deleted pages really gone?", body: ["Some tools only hide removed pages inside the file. PDFella rebuilds the document and removes every object that only belonged to deleted pages, so their text and images aren't carried along in the new PDF."] }],
    tips: ["To keep only a few pages, Extract PDF Pages may be faster."],
    useCases: [
      { who: "Anyone sharing documents", what: "Remove blank, duplicate or confidential pages before sending." },
      { who: "Students", what: "Delete cover and index pages from readings." },
      { who: "Admins", what: "Trim scanned batches down to what matters." },
    ],
    faq: [
      { q: "How do I remove a page from a PDF?", a: "Select the page in Delete PDF Pages, click Delete pages and download the new file." },
      { q: "Can I delete several pages at once?", a: "Yes. Click several thumbnails or type a range like 2-4, 7." },
      { q: "Is the deleted content really removed?", a: "Yes. Content that belonged only to deleted pages is removed from the file." },
      { q: "Is my file uploaded?", a: "No. Everything runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Can I undo a deletion?", a: "Your original file isn't changed; start again with it at any time." },
    ],
  },
  {
    slug: "extract-pdf-pages",
    keyword: "extract pdf pages",
    keywords: ["extract pages from pdf", "save pages from pdf", "pdf page extractor", "select pages from pdf"],
    metaTitle: "Extract PDF Pages Online: Save Pages as New PDF | PDFella",
    metaDescription: "Extract pages from a PDF into a new file. Click the pages you want or type a range and download them as one PDF. Free, private, no sign-up.",
    h1: "Extract pages from a PDF",
    subtitle: "Pick the pages you want and save them as a brand-new PDF. Your original stays untouched.",
    quickAnswer: "To extract pages from a PDF, open PDFella's Extract PDF Pages tool, upload the file, click the pages you want to keep (or type a range like 1-3, 8) and click Extract pages. Download the new PDF containing only those pages.",
    howToTitle: "How to extract pages from a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Choose the pages", body: "Click the thumbnails of the pages you want, or type a range such as 1-3, 8 and click Select.", shot: 2 },
      { title: "Click Extract pages", body: "The chosen pages are copied into a new PDF in their original order." },
      RESULT,
    ],
    benefits: [
      { title: "Original untouched", body: "A new PDF is created; your source file isn't changed." },
      { title: "Visual selection", body: "See every page before you choose." },
      PRIVATE,
      FREE,
    ],
    sections: [{ heading: "Extract vs. split", body: ["Extract creates one new PDF from the pages you pick. Split creates several PDFs at once, for example one per range or one per page."] }],
    tips: ["Type ranges for long documents: it's faster than clicking dozens of pages."],
    useCases: [
      { who: "Researchers", what: "Pull the relevant chapter out of a long report." },
      { who: "Lawyers", what: "Extract signed pages from a contract bundle." },
      { who: "Teachers", what: "Share only the pages students need." },
    ],
    faq: [
      { q: "How do I save just one page of a PDF?", a: "Select that page in Extract PDF Pages and click Extract pages." },
      { q: "Does extracting change my original PDF?", a: "No. A new PDF is created." },
      { q: "Can I extract non-consecutive pages?", a: "Yes. Click any pages or type a list like 1, 4, 9-10." },
      { q: "Is my file uploaded?", a: "No. Extraction happens in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Can I extract pages as images?", a: "Yes. Use PDF to JPG or PDF to PNG and choose the pages." },
    ],
  },
  {
    slug: "add-page-numbers-to-pdf",
    keyword: "add page numbers to pdf",
    keywords: ["number pdf pages", "pdf page numbering", "insert page numbers in pdf", "page x of y pdf"],
    metaTitle: "Add Page Numbers to PDF Online Free | PDFella",
    metaDescription: "Add page numbers to a PDF online. Choose the position, format (1 or Page 1 of 10), starting number and font size. Free, private, no sign-up.",
    h1: "Add page numbers to a PDF",
    subtitle: "Number your pages in any corner with formats like “1”, “Page 1” or “Page 1 of 10”.",
    quickAnswer: "To add page numbers to a PDF, open PDFella's Add Page Numbers tool, upload the file, pick a position (for example bottom centre), choose a format such as Page 1 of 10, set the starting number and click Add page numbers. Download the numbered PDF.",
    howToTitle: "How to add page numbers to a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Choose position and format", body: "Click one of six positions (top or bottom; left, centre or right), pick a format, set the start number, font size and margin, and optionally limit numbering to a page range. A live preview shows the result.", shot: 2 },
      { title: "Click Add page numbers", body: "Numbers are written into the PDF as real text, upright even on rotated pages." },
      RESULT,
    ],
    benefits: [
      { title: "Five formats", body: "1, Page 1, Page 1 of N, 1 / N and - 1 -." },
      { title: "Any start number", body: "Start at 0, 1 or any number, e.g. to continue another document." },
      { title: "Page ranges", body: "Skip the cover page by numbering only a range." },
      PRIVATE,
    ],
    sections: [{ heading: "Numbering everything except the cover", body: ["Enter a range such as 2- in the Pages box to skip the first page, and set Start at to 1 so numbering begins at 1 on the second page."] }],
    tips: ["Use Add Header and Footer if you also want the date or document name on each page."],
    useCases: [
      { who: "Students", what: "Number theses and dissertations." },
      { who: "Lawyers", what: "Paginate court bundles and exhibits." },
      { who: "Businesses", what: "Number reports and proposals." },
    ],
    faq: [
      { q: "How do I add Page 1 of 10 numbering?", a: "Choose the “Page 1 of N” format before clicking Add page numbers." },
      { q: "Can I skip the first page?", a: "Yes. Enter a page range such as 2- and set the start number." },
      { q: "Where can I place the numbers?", a: "Top or bottom; left, centre or right." },
      { q: "Is my file uploaded?", a: "No. Numbering happens in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Do numbers appear correctly on rotated pages?", a: "Yes. Numbers are placed upright relative to how each page is displayed." },
    ],
  },
  {
    slug: "add-header-and-footer-to-pdf",
    keyword: "add header and footer to pdf",
    keywords: ["pdf header footer", "add header to pdf", "add footer to pdf", "add date to pdf pages"],
    metaTitle: "Add Header and Footer to PDF Online Free | PDFella",
    metaDescription: "Add headers and footers to every PDF page: text, page numbers, the date and the file name, left, centre or right. Free, private, no sign-up.",
    h1: "Add a header and footer to a PDF",
    subtitle: "Put text, page numbers, the date or the document name at the top and bottom of every page.",
    quickAnswer: "To add a header and footer to a PDF, open PDFella's Header & Footer tool, upload the file and type into the left, centre and right boxes for the header and footer. Use {page}, {pages}, {date} and {name} for automatic values, then click Apply and download.",
    howToTitle: "How to add a header and footer to a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Type your header and footer", body: "Fill in any of the six boxes (left, centre, right for header and footer). Tokens {page}, {pages}, {date} and {name} are replaced automatically on each page.", shot: 2 },
      { title: "Click Apply", body: "Choose the font size and optional page range, then apply. Text is added as real, searchable text." },
      RESULT,
    ],
    benefits: [
      { title: "Smart tokens", body: "Page number, total pages, today's date and file name." },
      { title: "Six slots", body: "Left, centre and right in both header and footer." },
      { title: "Page ranges", body: "Apply to all pages or only some." },
      PRIVATE,
    ],
    sections: [{ heading: "Example header and footer", body: ["A common setup is the document name on the top left, the date on the top right, and 'Page {page} of {pages}' centred in the footer. That's the default, so most people can click Apply straight away."] }],
    tips: ["Keep header text short so it doesn't overlap the page content."],
    useCases: [
      { who: "Consultants", what: "Brand reports with the client name and date." },
      { who: "Legal teams", what: "Mark documents as drafts with the date on every page." },
      { who: "Students", what: "Add their name and page numbers to coursework." },
    ],
    faq: [
      { q: "Can I add the date to every page?", a: "Yes. Type {date} into any header or footer box." },
      { q: "Can I add page numbers too?", a: "Yes. Use {page} and {pages}, e.g. Page {page} of {pages}." },
      { q: "Is my file uploaded?", a: "No. Everything runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Can I choose which pages get a header?", a: "Yes. Enter a page range in the Pages box." },
      { q: "Is the header text searchable?", a: "Yes. It's written into the PDF as real text." },
    ],
  },
];
