import type { ToolContent } from "./types";

const UPLOAD = (where = "browser") => ({
  title: "Upload your PDF",
  body: where === "browser"
    ? "Drag your PDF onto the upload area or click Choose file. It's opened in your browser. Nothing is uploaded."
    : "Drag your PDF onto the upload area or click Choose file. It's sent over an encrypted connection to private, temporary storage for processing.",
  shot: 1,
});
const RESULT = { title: "Download the result", body: "Rename the file if you like and click Download, or open it in the editor to keep working.", shot: 3 };
const PRIVATE = { title: "Runs in your browser", body: "Your PDF never leaves your device." };
const FREE = { title: "Free, no account", body: "No sign-up, no watermark." };
const CLOUD = { title: "Secure cloud processing", body: "Processed in an isolated container and deleted automatically, within 60 minutes at most." };
const EDITOR_SAVE = { title: "Save and download", body: "Click Save changes, then Download PDF.", shot: 3 };

export const otherContent: ToolContent[] = [
  {
    slug: "compress-pdf",
    keyword: "compress pdf",
    keywords: ["pdf size reducer", "reduce pdf size", "pdf compressor", "shrink pdf", "compress pdf to 1mb", "make pdf smaller"],
    metaTitle: "Compress PDF Free: Reduce PDF File Size Online | PDFella",
    metaDescription: "Compress PDF files online for free. Reduce PDF size while keeping text sharp: choose Recommended, High compression or High quality. Private, no sign-up.",
    h1: "Compress PDF: reduce file size",
    subtitle: "Make PDFs smaller for email and uploads while keeping text sharp and selectable.",
    quickAnswer: "To compress a PDF, open PDFella's Compress PDF tool, upload the file, choose Recommended, High compression or High quality, and click Compress PDF. The tool shows the original and new size, for example 8.4 MB → 2.1 MB, and the percentage saved. Then download.",
    howToTitle: "How to compress a PDF",
    totalTime: "PT1M",
    steps: [
      UPLOAD(),
      { title: "Choose a compression level", body: "Recommended balances quality and size. High compression makes the smallest file with lower image quality. High quality keeps images crisp.", shot: 2 },
      { title: "Click Compress PDF", body: "Images inside the PDF are re-encoded and resized and unused data is removed. Text and vector graphics are untouched, so they stay sharp." },
      { title: "Check the saving and download", body: "The result shows the before and after size and the percentage saved. Click Download.", shot: 3 },
    ],
    benefits: [
      { title: "Text stays sharp", body: "Only images are recompressed; text remains selectable and searchable." },
      { title: "Three presets", body: "Recommended, High compression and High quality." },
      { title: "See the saving", body: "Original size, new size and percentage saved." },
      PRIVATE,
    ],
    sections: [
      { heading: "How much can a PDF be compressed?", body: ["It depends on what's inside. Scans and photo-heavy PDFs usually shrink by 50–90% because images make up most of their size. Text-only PDFs are already compact and may only shrink slightly. If a file is already well optimised, PDFella tells you rather than producing a bigger file."] },
      { heading: "Compressing a PDF for email or upload limits", body: ["Many email services cap attachments at 20–25 MB and online forms often require files under 1–5 MB. Start with Recommended; if the file is still too large, try High compression. For very large scans, splitting the document can also help."] },
    ],
    tips: ["Try High compression for scans that must be under a strict upload limit.", "If you merge PDFs, compress the merged file once at the end."],
    useCases: [
      { who: "Applicants", what: "Get documents under online form upload limits." },
      { who: "Office workers", what: "Email large reports without bouncing." },
      { who: "Archivists", what: "Save storage on scanned archives." },
    ],
    faq: [
      { q: "How do I reduce a PDF's file size for free?", a: "Upload the PDF to Compress PDF, choose a level and click Compress PDF. Download the smaller file. No account is needed." },
      { q: "Will compression reduce quality?", a: "Text and vector graphics are unchanged. Images are recompressed; choose High quality if image detail matters." },
      { q: "How much smaller will my PDF be?", a: "Image-heavy PDFs often shrink 50–90%. Text-only PDFs shrink less." },
      { q: "Is my PDF uploaded?", a: "No. Compression runs in your browser by default." },
      { q: "Can I compress a PDF to under 1 MB?", a: "Often, yes. Try High compression. Very long or image-heavy documents may need splitting too." },
      { q: "Is it free?", a: "Yes, with no account and no watermark." },
    ],
  },
  {
    slug: "ocr-pdf",
    keyword: "ocr pdf",
    keywords: ["make pdf searchable", "pdf ocr online", "scanned pdf to text", "searchable pdf", "ocr scanner"],
    metaTitle: "OCR PDF Online: Make Scanned PDFs Searchable | PDFella",
    metaDescription: "OCR scanned PDFs online. Recognise text in 100+ languages and add a searchable, selectable text layer while keeping the original look. Secure, no sign-up.",
    h1: "OCR PDF: make scanned PDFs searchable",
    subtitle: "Recognise the text in scanned PDFs so you can search, select and copy it, while the pages look exactly the same.",
    quickAnswer: "To make a scanned PDF searchable, open PDFella's OCR PDF tool, upload the scan, choose the document language and click OCR PDF. Text is recognised and added as an invisible layer behind each page image, so you can search, select and copy it. Download the searchable PDF.",
    howToTitle: "How to OCR a PDF",
    totalTime: "PT2M",
    steps: [UPLOAD("cloud"), { title: "Choose the language", body: "Pick the language of the document for the most accurate recognition, then click OCR PDF. Progress is shown as a percentage.", shot: 2 }, RESULT],
    benefits: [
      { title: "Searchable & selectable", body: "Find words with Ctrl/⌘ + F and copy text." },
      { title: "Looks identical", body: "The original scan stays visible; text is added behind it." },
      { title: "Straightens pages", body: "Pages are deskewed and auto-rotated." },
      CLOUD,
    ],
    sections: [
      { heading: "What is OCR?", body: ["Optical character recognition (OCR) turns pictures of text, like scanned pages or photos of documents, into real text a computer can read. A scanned PDF without OCR is just a set of images: you can't search it, copy from it or convert it to Word accurately."] },
      { heading: "Tips for accurate OCR", body: ["Scan at 300 DPI where possible, keep pages flat and well lit, and choose the correct language. Clean, high-contrast scans give the best results."] },
    ],
    tips: ["After OCR, use PDF to Word to get an editable document.", "In the editor, scanned PDFs show a Run OCR button automatically."],
    useCases: [
      { who: "Archivists", what: "Make scanned archives searchable." },
      { who: "Lawyers", what: "Search scanned case bundles for names and dates." },
      { who: "Accountants", what: "Copy figures from scanned invoices." },
    ],
    faq: [
      { q: "How do I make a scanned PDF searchable?", a: "Upload it to OCR PDF, choose the language and run OCR. The downloaded PDF has a searchable text layer." },
      { q: "Will the PDF look different?", a: "No. The original page images are kept; the text layer is invisible." },
      { q: "Which languages are supported?", a: "English, German, French, Spanish, Italian, Portuguese, Dutch, Hindi, Nepali, Arabic, Chinese (Simplified) and Japanese are available in the tool, and more can be enabled." },
      { q: "Is my file uploaded?", a: "Yes. OCR uses secure cloud processing and files are deleted automatically, within 60 minutes at most." },
      { q: "Can I convert the OCR result to Word?", a: "Yes. Run PDF to Word on the searchable PDF." },
      { q: "Is it free?", a: "Yes, within the daily allowance for cloud tools." },
    ],
  },
  {
    slug: "repair-pdf",
    keyword: "repair pdf",
    keywords: ["fix corrupted pdf", "pdf repair online", "pdf won't open", "recover pdf"],
    metaTitle: "Repair PDF Online: Fix Corrupted PDF Files Free | PDFella",
    metaDescription: "Repair damaged or corrupted PDF files online. Rebuild broken structure so the PDF opens again. Free, private, runs in your browser.",
    h1: "Repair a corrupted PDF",
    subtitle: "Rebuild a damaged PDF's internal structure so it opens again.",
    quickAnswer: "To repair a PDF, open PDFella's Repair PDF tool and upload the damaged file. It reconstructs the PDF's cross-reference table and object structure in your browser and gives you a repaired copy to download, recovering every page that can still be read.",
    howToTitle: "How to repair a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD(), { title: "Let it rebuild", body: "Repair starts automatically and rebuilds the file's structure.", shot: 2 }, RESULT],
    benefits: [{ title: "Rebuilds structure", body: "Fixes broken cross-reference tables and trailers." }, { title: "Recovers pages", body: "Every readable page is kept." }, PRIVATE, FREE],
    sections: [{ heading: "Why do PDFs get corrupted?", body: ["Interrupted downloads, failed email attachments, disk errors and buggy software can leave a PDF with a damaged index. The page content is often still there; rebuilding the index makes the file readable again. Severely truncated files may only be partly recoverable."] }],
    tips: ["Try re-downloading the original file first if it came from email or the web."],
    useCases: [
      { who: "Anyone", what: "Rescue a PDF that won't open after a broken download." },
      { who: "IT support", what: "Fix files that show 'damaged' errors." },
      { who: "Archivists", what: "Recover old documents with structural errors." },
    ],
    faq: [
      { q: "Can every PDF be repaired?", a: "Most PDFs with structural damage can. Files missing large parts of their content may only be partly recoverable." },
      { q: "Is my file uploaded?", a: "No. Repair runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Will repaired text still be searchable?", a: "Yes, if the original text survived." },
      { q: "What if repair fails?", a: "The file is probably too damaged; try obtaining a fresh copy of the original." },
      { q: "Does it work on password-protected PDFs?", a: "Unlock the PDF first, then repair it." },
    ],
  },
  {
    slug: "flatten-pdf",
    keyword: "flatten pdf",
    keywords: ["flatten pdf form", "make pdf non editable", "flatten pdf online", "lock pdf form fields"],
    metaTitle: "Flatten PDF Online Free: Make Forms Non-Editable | PDFella",
    metaDescription: "Flatten a PDF online to turn form fields and their values into regular page content so they can't be changed. Free, private, no sign-up.",
    h1: "Flatten PDF",
    subtitle: "Turn form fields into regular page content, keeping their values but making them non-editable.",
    quickAnswer: "To flatten a PDF, open PDFella's Flatten PDF tool, upload the file and click Flatten PDF. Form fields and their current values become part of the page, so they look the same but can no longer be edited. Download the flattened PDF.",
    howToTitle: "How to flatten a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD(), { title: "Click Flatten PDF", body: "Every form field is converted into page content with its current value.", shot: 2 }, RESULT],
    benefits: [{ title: "Values kept", body: "Filled-in answers stay exactly as they appear." }, { title: "Can't be changed", body: "Fields are no longer editable in any reader." }, PRIVATE, FREE],
    sections: [{ heading: "When should you flatten a PDF?", body: ["Flatten forms before sending them back so answers can't be changed, before printing to ensure every value appears, or before archiving. You can also flatten while saving in the editor."] }],
    tips: ["Fill the form first with Fill PDF, then flatten when saving."],
    useCases: [
      { who: "HR", what: "Lock completed onboarding forms." },
      { who: "Lawyers", what: "Finalise filled court forms." },
      { who: "Anyone", what: "Make sure printed forms show every answer." },
    ],
    faq: [
      { q: "What does flattening a PDF do?", a: "It converts form fields into normal page content so their values can't be edited." },
      { q: "Will my answers disappear?", a: "No. Current values are kept on the page." },
      { q: "Is my file uploaded?", a: "No. Flattening runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Can I undo flattening?", a: "Not in the flattened file. Keep your original if you might need to edit it." },
      { q: "Can I flatten while filling a form?", a: "Yes. Choose Flatten form fields in the editor's save dialog." },
    ],
  },
  {
    slug: "protect-pdf",
    keyword: "password protect pdf",
    keywords: ["protect pdf", "encrypt pdf", "add password to pdf", "lock pdf", "secure pdf"],
    metaTitle: "Password Protect PDF Free: Encrypt with AES-256 | PDFella",
    metaDescription: "Password protect a PDF online with AES-256 encryption. Control printing, copying and editing. Encrypted in your browser, so nothing is uploaded. Free.",
    h1: "Password protect a PDF",
    subtitle: "Encrypt a PDF with AES-256 so it needs a password to open, right in your browser.",
    quickAnswer: "To password protect a PDF, open PDFella's Protect PDF tool, upload the file, type and confirm a password, choose whether printing, copying and editing are allowed, and click Protect PDF. The file is encrypted with AES-256 in your browser and downloaded.",
    howToTitle: "How to password protect a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD(), { title: "Set a password and permissions", body: "Enter the password twice and choose whether to allow printing, copying text and editing.", shot: 2 }, { title: "Click Protect PDF", body: "The PDF is encrypted with AES-256 on your device." }, RESULT],
    benefits: [{ title: "AES-256 encryption", body: "The strongest standard PDF encryption." }, { title: "Permissions", body: "Allow or block printing, copying and editing." }, { title: "Password stays private", body: "Encryption happens in your browser; your password is never sent anywhere." }, FREE],
    sections: [{ heading: "Choosing a strong PDF password", body: ["Use at least 12 characters, ideally a passphrase of several unrelated words. Share the password through a different channel than the file, for example send the PDF by email and the password by text message. PDFella can't recover a forgotten password."] }],
    tips: ["Send the password separately from the document."],
    useCases: [
      { who: "Accountants", what: "Protect tax returns and statements before emailing." },
      { who: "HR", what: "Secure payslips and contracts." },
      { who: "Anyone", what: "Protect ID documents and medical records." },
    ],
    faq: [
      { q: "How do I add a password to a PDF for free?", a: "Upload it to Protect PDF, enter a password, choose permissions and click Protect PDF." },
      { q: "What encryption is used?", a: "AES-256, the strongest standard PDF encryption." },
      { q: "Is my PDF or password uploaded?", a: "No. Encryption happens entirely in your browser." },
      { q: "Can you recover my password?", a: "No. Keep it somewhere safe." },
      { q: "Can I stop people printing or copying?", a: "Yes. Turn off printing, copying or editing permissions." },
      { q: "How do I remove the password later?", a: "Use Unlock PDF with the password." },
    ],
  },
  {
    slug: "unlock-pdf",
    keyword: "unlock pdf",
    keywords: ["remove password from pdf", "pdf password remover", "unlock pdf online", "remove pdf restrictions"],
    metaTitle: "Unlock PDF Free: Remove Password & Restrictions | PDFella",
    metaDescription: "Unlock PDFs online. Remove printing, copying and editing restrictions automatically, or remove the open password when you know it. Private, free.",
    h1: "Unlock PDF",
    subtitle: "Remove printing, copying and editing restrictions automatically, or remove the open password you know.",
    quickAnswer: "To unlock a PDF, open PDFella's Unlock PDF tool and upload the file. Restrictions on printing, copying and editing are removed automatically. If the PDF needs a password to open, enter it once. Download the unlocked PDF, which no longer asks for a password.",
    howToTitle: "How to unlock a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD(), { title: "Enter the password if asked", body: "Restriction-only PDFs unlock instantly. If the file needs a password to open, a prompt asks for it once.", shot: 2 }, RESULT],
    benefits: [{ title: "Restrictions removed", body: "Print, copy and edit freely." }, { title: "Password removed", body: "No more prompts every time you open it." }, PRIVATE, FREE],
    sections: [
      { heading: "Two kinds of PDF passwords", body: ["An owner (permissions) password restricts what you can do with a PDF you can already open, such as printing or copying. An open (user) password is needed to view the PDF at all. PDFella removes permission restrictions automatically and removes an open password when you provide it."] },
      { heading: "Can you unlock a PDF without the password?", body: ["If a PDF needs a password to open, it's encrypted with that password, and it can't be unlocked without it. Only unlock documents you own or have permission to use."] },
    ],
    tips: ["Every PDFella tool unlocks PDFs automatically, so you can go straight to editing or merging."],
    useCases: [
      { who: "Employees", what: "Print a restricted statement or policy." },
      { who: "Accountants", what: "Open client PDFs without re-entering passwords." },
      { who: "Students", what: "Copy quotes from restricted readings for citations." },
    ],
    faq: [
      { q: "How do I remove a password from a PDF?", a: "Upload it to Unlock PDF and enter the password once. Download the unlocked file." },
      { q: "Can I unlock a PDF without the password?", a: "Restrictions on printing and copying are removed automatically. A password required to open the file can't be bypassed." },
      { q: "Is my file or password uploaded?", a: "No. Unlocking happens in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
      { q: "Do I need to unlock PDFs before using other tools?", a: "No. Every tool unlocks protected PDFs automatically." },
      { q: "Is it legal to unlock a PDF?", a: "Unlock only documents you own or are authorised to use." },
    ],
  },
  {
    slug: "redact-pdf",
    keyword: "redact pdf",
    keywords: ["redact pdf online", "black out text in pdf", "remove sensitive information from pdf", "pdf redaction tool"],
    metaTitle: "Redact PDF Online Free: Permanently Remove Text | PDFella",
    metaDescription: "Redact PDFs online. Black out text or areas and permanently remove them from the file, not just cover them. Find and redact every match. Free, private.",
    h1: "Redact PDF",
    subtitle: "Permanently remove sensitive text and images: redacted content is deleted from the file, not just hidden.",
    quickAnswer: "To redact a PDF, open it in PDFella, choose Redact and drag across the text or area to remove, or press Ctrl/⌘ + F and mark every match at once. Preview the redactions, then click Save changes. Redacted content is permanently deleted from the downloaded PDF.",
    howToTitle: "How to redact a PDF",
    totalTime: "PT2M",
    steps: [
      { title: "Upload your PDF", body: "Drop the PDF onto the upload area. It opens in the editor with the Redact tool selected.", shot: 1 },
      { title: "Mark what to remove", body: "Drag across text (it snaps to lines) or any area. To redact every occurrence of a word or number, press Ctrl/⌘ + F, search, and click Mark all matches for redaction.", shot: 2 },
      { title: "Preview and apply", body: "Click Preview redactions to see the result, then Save changes. Redacted content is removed from the file." },
      EDITOR_SAVE,
    ],
    benefits: [
      { title: "Truly removed", body: "Redacted text can't be selected, searched or copied afterwards." },
      { title: "Find & redact", body: "Search and mark every match in one click." },
      { title: "Rest stays searchable", body: "Unredacted text remains searchable." },
      PRIVATE,
    ],
    sections: [
      { heading: "Why a black box isn't redaction", body: ["Drawing a black rectangle over text only hides it visually: the words are still in the file and can be copied out. Proper redaction deletes the underlying content. PDFella rebuilds pages that contain redactions so the removed text and images no longer exist in the PDF, while keeping a searchable text layer for everything you didn't redact."] },
      { heading: "Checking your redactions", body: ["After downloading, open the PDF and try to select or search for the redacted text. It won't be found. Also review the whole document, including headers, footers and attachments, for anything you may have missed."] },
    ],
    tips: ["Use search to redact every instance of a name or account number.", "Redaction flattens form fields to make sure no hidden values remain."],
    useCases: [
      { who: "Legal teams", what: "Redact privileged information before disclosure." },
      { who: "HR", what: "Remove personal data before sharing documents." },
      { who: "Public bodies", what: "Prepare documents for freedom-of-information requests." },
    ],
    faq: [
      { q: "Is redaction permanent?", a: "Yes. Redacted content is removed from the downloaded file and can't be recovered from it." },
      { q: "Can I redact every occurrence of a word?", a: "Yes. Search with Ctrl/⌘ + F and click Mark all matches for redaction." },
      { q: "Is my PDF uploaded?", a: "No. Redaction runs in your browser by default." },
      { q: "Will the rest of the document stay searchable?", a: "Yes. Text outside redacted areas remains searchable." },
      { q: "Can I change the redaction colour?", a: "Yes. Choose black, white or grey." },
      { q: "Is it free?", a: "Yes, with no account." },
    ],
  },
  {
    slug: "watermark-pdf",
    keyword: "watermark pdf",
    keywords: ["add watermark to pdf", "pdf watermark online", "stamp pdf", "confidential watermark pdf"],
    metaTitle: "Add Watermark to PDF Online Free: Text or Logo | PDFella",
    metaDescription: "Add a text or image watermark to a PDF online. Set opacity, rotation, position and pages, or tile it across the page. Free, private, no sign-up.",
    h1: "Add a watermark to a PDF",
    subtitle: "Stamp text like CONFIDENTIAL or your logo onto pages, with full control over look and position.",
    quickAnswer: "To watermark a PDF, open PDFella's Watermark tool, upload the file, type your watermark text or choose a logo image, set opacity, rotation, size and position (or tile it), optionally limit it to certain pages, then click Add watermark and download.",
    howToTitle: "How to add a watermark to a PDF",
    totalTime: "PT1M",
    steps: [UPLOAD(), { title: "Design your watermark", body: "Choose Text or Image. Set font, size, colour, opacity and rotation, pick one of nine positions or tile across the page, and choose whether it sits on top of or behind content. A live preview shows the first page.", shot: 2 }, { title: "Click Add watermark", body: "The watermark is written onto the selected pages." }, RESULT],
    benefits: [{ title: "Text or logo", body: "Type any text or use a PNG/JPG logo." }, { title: "Live preview", body: "See exactly how it looks before applying." }, { title: "Behind or on top", body: "Place it under the content for a subtle mark." }, PRIVATE],
    sections: [{ heading: "Choosing watermark settings", body: ["For drafts and confidential documents, a diagonal text watermark at 20–30% opacity is clearly visible but leaves the content readable. For branding, a small logo in a corner at higher opacity works best. Tiling makes it harder to crop the watermark out."] }],
    tips: ["Use Place behind content so the watermark doesn't cover text."],
    useCases: [
      { who: "Businesses", what: "Mark drafts as DRAFT or CONFIDENTIAL." },
      { who: "Photographers", what: "Brand portfolio PDFs with a logo." },
      { who: "Publishers", what: "Watermark review copies." },
    ],
    faq: [
      { q: "How do I add a watermark to a PDF for free?", a: "Upload it to Watermark, set your text or image and click Add watermark." },
      { q: "Can I use my logo?", a: "Yes. Choose Image and upload a PNG or JPG." },
      { q: "Can I watermark only some pages?", a: "Yes. Enter a page range." },
      { q: "Is my file uploaded?", a: "No. Watermarking runs in your browser." },
      { q: "Can I place the watermark behind the text?", a: "Yes. Turn on Place behind content." },
      { q: "Is it free?", a: "Yes, with no account." },
    ],
  },
  {
    slug: "fill-pdf",
    keyword: "fill pdf",
    keywords: ["fill pdf form", "fill out pdf online", "fill in pdf", "complete pdf form", "pdf form filler"],
    metaTitle: "Fill PDF Forms Online Free: Fill Out & Sign | PDFella",
    metaDescription: "Fill out PDF forms online. Complete text fields, checkboxes and dropdowns, type on non-fillable forms, sign and download. Free, private, no sign-up.",
    h1: "Fill PDF forms online",
    subtitle: "Complete fillable PDF forms, type on forms that aren't fillable, sign and download.",
    quickAnswer: "To fill a PDF form, open it in PDFella. Fillable fields are listed in the Form fields panel, where you type answers, tick checkboxes and choose dropdown options. For non-fillable forms use Add text. Sign with Sign, then click Save changes and Download PDF.",
    howToTitle: "How to fill out a PDF form",
    totalTime: "PT3M",
    steps: [
      { title: "Upload your form", body: "Drop the PDF form onto the upload area. It opens in the editor.", shot: 1 },
      { title: "Fill in the fields", body: "Fillable fields appear in the Form fields panel on the right. Type answers, tick boxes and pick options. For forms without fields, choose Add text and click on each line.", shot: 2 },
      { title: "Sign and save", body: "Add your signature with Sign. When saving, optionally flatten the form so answers can't be changed, then download.", shot: 3 },
    ],
    benefits: [{ title: "Detects fields", body: "Text fields, checkboxes, radio buttons and dropdowns." }, { title: "Non-fillable forms too", body: "Type anywhere with Add text." }, { title: "Sign in place", body: "Add a typed, drawn or uploaded signature." }, PRIVATE],
    sections: [{ heading: "Fillable vs. non-fillable PDF forms", body: ["Fillable forms contain interactive fields that PDFella lists in the Form fields panel. Many forms are simply scanned or flat PDFs with lines to write on: for those, use Add text and place your answers on the lines, nudging with the arrow keys for precise alignment."] }],
    tips: ["Choose Flatten form fields when saving so answers can't be altered."],
    useCases: [
      { who: "Applicants", what: "Complete visa, job and university applications." },
      { who: "Tenants", what: "Fill and sign rental forms." },
      { who: "Patients", what: "Complete registration forms before an appointment." },
    ],
    faq: [
      { q: "How do I fill out a PDF form for free?", a: "Open it in PDFella, complete the fields in the Form fields panel (or use Add text), then save and download." },
      { q: "What if the form isn't fillable?", a: "Use Add text to type on any line or box." },
      { q: "Can I sign the form?", a: "Yes. Use Sign to add your signature." },
      { q: "Is my form uploaded?", a: "No. Filling happens in your browser." },
      { q: "Will my answers show in other PDF readers?", a: "Yes. Values are written into the form fields." },
      { q: "Is it free?", a: "Yes, with no account." },
    ],
  },
  {
    slug: "create-pdf-form",
    keyword: "create fillable pdf",
    keywords: ["create pdf form", "make pdf fillable", "fillable pdf maker", "add form fields to pdf"],
    metaTitle: "Create Fillable PDF Forms Online Free | PDFella",
    metaDescription: "Make any PDF fillable online. Add text fields, checkboxes, radio buttons, dropdowns, date and signature fields that work in every PDF reader. Free.",
    h1: "Create a fillable PDF form",
    subtitle: "Turn any PDF into a fillable form with text fields, checkboxes, radio buttons, dropdowns, date and signature fields.",
    quickAnswer: "To create a fillable PDF, open it in PDFella, choose Form field, pick a type (text, checkbox, radio, dropdown, date or signature) and drag a box where the field should go. Name each field, set options, then save and download. Fields work in any PDF reader.",
    howToTitle: "How to create a fillable PDF form",
    totalTime: "PT5M",
    steps: [
      { title: "Upload your PDF", body: "Drop the document onto the upload area. It opens in the editor with the Form field tool selected.", shot: 1 },
      { title: "Draw form fields", body: "Choose a field type in the side panel and drag a box over each answer area. Click to place checkboxes and radio buttons.", shot: 2 },
      { title: "Name fields and set options", body: "Select a field to rename it, mark it required, add dropdown options or group radio buttons." },
      EDITOR_SAVE,
    ],
    benefits: [{ title: "Six field types", body: "Text, checkbox, radio, dropdown, date and signature." }, { title: "Standard AcroForms", body: "Works in Acrobat, Preview, Edge and Chrome." }, { title: "Date validation", body: "Date fields use a consistent format." }, PRIVATE],
    sections: [{ heading: "Designing a good PDF form", body: ["Give every field a clear, unique name. It becomes the key when you collect answers. Group yes/no and multiple-choice answers as radio buttons in the same group, mark required fields, and leave enough room in text fields for long answers."] }],
    tips: ["Use radio buttons with the same group name for multiple-choice questions."],
    useCases: [
      { who: "HR", what: "Turn onboarding documents into fillable forms." },
      { who: "Schools", what: "Create permission slips parents can complete online." },
      { who: "Small businesses", what: "Make order and feedback forms." },
    ],
    faq: [
      { q: "How do I make a PDF fillable for free?", a: "Open it in PDFella, use Form field to draw fields, then save and download." },
      { q: "Will the form work in Adobe Reader?", a: "Yes. Fields are standard PDF form fields." },
      { q: "Can I add a signature field?", a: "Yes. Choose Signature as the field type." },
      { q: "Can I add dropdown options?", a: "Yes. Select the dropdown and enter one option per line." },
      { q: "Is my document uploaded?", a: "No. Everything runs in your browser." },
      { q: "Is it free?", a: "Yes, with no account." },
    ],
  },
];
